\COPY users (accepted_date,email,id,language,language_1,last_access_date,login,name) FROM 'migrations/users.csv' WITH CSV HEADER
\COPY cases (communication_mode,communication_with_audience,content_country,decision_method,end_date,facetoface_online_or_both,facilitated,id,issue,kind_of_influence,location,number_of_meeting_days,ongoing,original_language,participant_selection,post_date,published,specific_topic,staff_type,start_date,targeted_audience,targeted_participant_demographic,targeted_participants_public_role,total_number_of_participants,type_of_funding_entity,typical_implementing_entity,typical_sponsoring_entity,updated_date,voting,who_else_supported_the_initiative,who_was_primarily_responsible_for_organizing_the_initiative) FROM 'migrations/cases.csv' WITH CSV HEADER
\COPY case__localized_texts (body,case_id,language,title) FROM 'migrations/case__localized_texts.csv' WITH CSV HEADER
\COPY case__authors (author,case_id,timestamp) FROM 'migrations/case__authors.csv' WITH CSV HEADER
\COPY case__attachments (case_id,is_lead,size,title,type,url) FROM 'migrations/case__attachments.csv' WITH CSV HEADER
\COPY case__tags (case_id,tag) FROM 'migrations/case__tags.csv' WITH CSV HEADER
\COPY case__videos (case_id,title,url) FROM 'migrations/case__videos.csv' WITH CSV HEADER
\COPY methods (best_for,communication_mode,decision_method,facilitated,governance_contribution,id,issue_interdependency,issue_polarization,issue_technical_complexity,kind_of_influence,method_of_interaction,original_language,post_date,public_interaction_method,published,typical_funding_source,typical_sponsoring_entity,updated_date) FROM 'migrations/methods.csv' WITH CSV HEADER
\COPY method__localized_texts (body,language,method_id,title) FROM 'migrations/method__localized_texts.csv' WITH CSV HEADER
\COPY method__authors (author,method_id,timestamp) FROM 'migrations/method__authors.csv' WITH CSV HEADER
\COPY method__attachments (is_lead,method_id,size,title,type,url) FROM 'migrations/method__attachments.csv' WITH CSV HEADER
\COPY method__tags (method_id,tag) FROM 'migrations/method__tags.csv' WITH CSV HEADER
\COPY method__videos () FROM 'migrations/method__videos.csv' WITH CSV HEADER
\COPY organizations (executive_director,id,issue,location,original_language,post_date,published,sector,updated_date) FROM 'migrations/organizations.csv' WITH CSV HEADER
\COPY organization__localized_texts (body,language,organization_id,title) FROM 'migrations/organization__localized_texts.csv' WITH CSV HEADER
\COPY organization__authors (author,organization_id,timestamp) FROM 'migrations/organization__authors.csv' WITH CSV HEADER
\COPY organization__attachments (is_lead,organization_id,size,title,type,url) FROM 'migrations/organization__attachments.csv' WITH CSV HEADER
\COPY organization__tags (organization_id,tag) FROM 'migrations/organization__tags.csv' WITH CSV HEADER
\COPY organization__videos (organization_id,title,url) FROM 'migrations/organization__videos.csv' WITH CSV HEADER
\COPY geolocation (address1,address2,city,country,id,latitude,longitude,name,postal_code,province) FROM 'migrations/geolocation.csv' WITH CSV HEADER
