CREATE TABLE layout_localized (
  language TEXT NOT NULL,
  home_label TEXT DEFAULT 'Localized home_label',
  about_label TEXT DEFAULT 'Localized about_label',
  teaching_label TEXT DEFAULT 'Localized teaching_label',
  research_label TEXT DEFAULT 'Localized research_label',
  help_label TEXT DEFAULT 'Localized help_label',
  terms_label TEXT DEFAULT 'Localized terms_label',
  feedback_label TEXT DEFAULT 'Localized feedback_label',
  search_label TEXT DEFAULT 'Localized search_label',
  quick_submit_label TEXT DEFAULT 'Localized quick_submit_label',
  login_label TEXT DEFAULT 'Localized login_label',
  profile_label TEXT DEFAULT 'Localized profile_label',
  sign_out_label TEXT DEFAULT 'Localized sign_out_label',
  all_tab_label TEXT DEFAULT 'Localized all_tab_label',
  cases_tab_label TEXT DEFAULT 'Localized cases_tab_label',
  methods_tab_label TEXT DEFAUlT 'Localized methods_tab_label',
  tools_tab_label TEXT DEFAULT 'Localized tools_tab_label',
  organizations_tab_label TEXT DEFAULT 'Localized organizations_tab_label',
  resources_tab_label TEXT DEFAULT 'Localized resources_tab_label',
  users_tab_label TEXT DEFAULT 'Localized users_tab_label',
  news_tab_label TEXT DEFAULT 'Localized news_tab_label',
  page_label TEXT DEFAULT 'Localized page_label',
  page_count_label TEXT DEFAULT 'Localized page_count_label',
  experiments_label TEXT DEFAULT 'Localized experiments_label',
  tagline TEXT DEFAULT 'Localized tagline',
  grid_layout TEXT DEFAULT 'Localized grid_layout',
  list_layout TEXT DEFAULT 'Localized list_layout',
  download_label TEXT DEFAULT 'Localized download_label',
  updated_date_label TEXT DEFAULT 'Localized updated_date_label',
  submitted_date_label TEXT DEFAULT 'Localized submitted_date_label'
);

INSERT INTO layout_localized VALUES (
  'en',
  'Home',
  'About',
  'Teaching',
  'Research',
  'Help & Contact',
  'Terms of Use',
  'Feedback',
  'Search',
  'Quick Submit',
  'Login',
  'Profile',
  'Sign Out',
  'All',
  'Cases',
  'Methods',
  'Tools',
  'Organizations',
  'Resources',
  'Users',
  'News',
  'Page',
  'of',
  'Experiments',
  'A global community sharing knowledge and stories about public participation',
  'grid',
  'list',
  'Download',
  'Submitted',
  'Last Updated'
);
