INSERT INTO case_static_localized VALUES (
  'en',
  'Title of Case',
  'Give this public participation project or event a descriptive title in 10 words or less. For example, “Brazilian Dialogue on Diversity" or "New York City Public Issues Forum."',
  '',
  'Enter title in 10 words or less',
  'General Issues',
  'Rank order up to three of the most relevant issues addressed, with "1" indicating the most relevant issue. You will be asked to provide more detailed information in the Specific Topics field below.',
  '',
  'Select & rank up to 3 issues',
  'Brief Description',
  'Enter tweet-length (280 characters or less) description of this case.',
  '',
  'Enter tweet-length description',
  'Narrative',
  'The following standard structure makes it easier to compare and analyze entries. Please use the headings below and refer to our guidelines as you prepare your case entry.',
  '',
  'Problems and Purpose Background History and Context Organizing, Supporting, and Funding Entities Participant Recruitment and Selection Methods and Tools Used Deliberation, Decisions, and Public Interaction Influence, Outcomes, and Effects Analysis and Lessons Learned See Also References External Links Notes',
  'Tags',
  'Select the tags that best describe this case.',
  '',
  'Enter one or more tags',
  'Primary Location',
  'Type to select an address, city or country where the primary case activities occurred. List any additional locations in the case narrative under "Originating Entities and Funding". You may also want to create separate case components for the locations of other case activities.',
  '',
  'Type to search for a known location',
  'Scope of Influence',
  'Select geographical or jurisdictional scope',
  '',
  'Select geographical or jurisdictional scope',
  'Add Components to this Case',
  'A case can have multiple components, but they must already be published cases on Participedia. Type to search for an existing case in Participedia to label it as a component of this case. Select one or more.',
  'If you cannot find the case you are looking for, first publish this entry to save your work. Next use quick submit to publish the component case entry. Then return to this case entry and add your new case entry as a component.',
  'Search for existing case/component',
  'Make This Case a Component of Another Case',
  'A case can only be a component of one other case, and the other case must already be published on Participedia. Type to search for an existing case in Participedia to label this case as a component of it. Select one.',
  'If you cannot find the case you are looking for, first publish this entry to save your work. Next use quick submit to publish the ‘parent’ case entry. Then return to this case entry and label this case as a component of the new ‘parent’ case.',
  'Search for existing case/parent',
  'Files',
  'Upload relevant documents here. Supported file types include: rtf, txt, doc, docx, xls, xlsx, pdf, ppt, pptx, pps, ppsx, odt, ods and odp.',
  '',
  'Add file',
  'Source Link',
  'If applicable, provide a link to where the original file was sourced.',
  '',
  'Link to Original',
  'Attribution',
  'Who is the original owner or creator of this file?',
  '',
  'Owner or creator',
  'Title or Description',
  'Provide the original title or description of this file in ten words or less.',
  ',',
  'Title or description',
  'Links',
  'If there is a main website for this case, enter it here. Add links to additional sources so that readers and editors can find more information about this case online.',
  '',
  'Add link',
  'Attribution',
  'Who is the original owner or creator of this linked content?',
  '',
  'Owner or creator',
  'Title or Description',
  'Provide the original title or description of this linked content in ten words or less.',
  '',
  'Title or description',
  'Photos',
  'Select a photo from your device',
  '',
  'Select a photo from your device',
  'Source Link',
  'If applicable, provide a link to where the original photo was sourced.',
  '',
  'Link to original',
  'Attribution',
  'Who is the original owner or creator of this photo?',
  '',
  'Owner or creator',
  'Title or Description',
  'Provide the original title or description of this photo in ten words or less.',
  ',',
  'Title or description',
  'Videos',
  'Add a video link from Vimeo or YouTube.',
  '',
  'Add a video link (Vimeo or YouTube)',
  'Attribution',
  'Who is the original owner or creator of this video?',
  '',
  'Owner or creator',
  'Title or Description',
  'Provide the original title or description of this video.',
  '',
  'Title or description',
  'Audio',
  'Add a link to audio',
  '',
  'Add link to audio',
  'Attribution',
  'Owner or creator',
  '',
  'Owner or creator',
  'Title or Description',
  'Provide the original title or description of the audio.',
  '',
  'Title or description',
  'Start Date',
  'Select a start date or date of single event.',
  '',
  'Select a start date or date of single event',
  'End Date',
  'Select an end date if applicable',
  '',
  'Select an end date if applicable',
  'This case is ongoing',
  'null',
  '',
  'null',
  'Time Limited or Repeated?',
  'Did this case take place over a single, defined period of days, weeks or months? Or was the entire process repeated over time? Select one.',
  '',
  'Was this time limited or repeated?',
  'Purpose/Goal',
  'Select and rank up to three purposes, with "1" indicating the most relevant.',
  '',
  'Select & rank up to 3 purposes/goals',
  'Approach',
  'Select and rank up to three approaches, with “1” indicating the most relevant.',
  '',
  'Select & rank up to 3 approaches',
  'Spectrum of Public Participation',
  'Which type of goal from the IAP2 Spectrum of Public Participation does this case best represent?',
  '',
  'Select one goal',
  'Total Number of Participants',
  'Roughly how many people participated?',
  '',
  'How many people participated?',
  'Open to All or Limited to Some?',
  'Was this open to all or limited to a subset of the population?',
  '',
  'Was this open to all or limited to some?',
  'Recruitment Method for Limited Subset of Population',
  'If relevant to this case, select the method used to recruit a limited subset of the population.',
  '',
  'Select recruitment method',
  'Targeted Demographics',
  'Select up to three of the most heavily recruited groups',
  '',
  'Identify up to 3 recruited groups',
  'General Types of Methods',
  'Select and rank up to three types that best describe the methods used in this case, with "1" indicating the most relevant.',
  'There is huge variety in the range of participatory methods. To help narrow it down, select and rank up to three of the following types of methods used in this case. Specifying what types of methods were used makes it easier for Participedia users to find similar cases.',
  'Select & rank up to 3 types',
  'General Types of Tools/Techniques',
  'Select and rank up to three types that best describe the tools/techniques used in this case, with “1” indicating the most relevant.',
  'There is huge variety in the range of participatory tools/techniques. To help narrow it down, select and rank up to three of the following types that best describe the specific tools/techniques used in this case. Specifying what types of tools/techniques were used is makes it easier for Participedia users to find similar cases.',
  'Select & rank up to 3 types',
  'Specific Methods, Tools & Techniques',
  'What specific methods, tools and techniques were used in this case? Type to select from entries already in the Participedia database.',
  '',
  'Type to search & generate possible database matches',
  'Legality',
  'Is the overall method used in this case considered legal by judicial authorities?',
  '',
  'Was this considered legal?',
  'Facilitators',
  'Did facilitators help guide part or all of this case?',
  '',
  'Was this considered legal?',
  'Facilitator Training',
  'What level of training did facilitators have?',
  '',
  'Select the type of facilitators',
  'Face-to-Face, Online, or Both',
  'Did participants interact face-to-face, online, or both?',
  '',
  'Was interaction face-to-face or online?',
  'Types of Interaction Among Participants',
  'Select and rank up to three types of interactions in order of relevance, with with “1” indicating the most often used form of interaction.',
  '',
  'Select & rank up to 3 types of interaction',
  'Information & Learning Resources',
  'What types of background information were provided for participants?',
  '',
  'Identify information (if any) provided',
  'Decision Methods',
  'How did participants in this case make group decisions?',
  '',
  'How were group decisions made?',
  'If Voting',
  'What voting methods were used by participants?',
  '',
  'What voting methods were used?',
  'Communication of Insights & Outcomes',
  'Select up to three ways that insights and outcomes from this case were communicated to the intended audiences.',
  '',
  'How were insights & outcomes communicated?',
  'Primary Organizer/Manager',
  'Who was primarily responsible for organizing / managing the initiative? Type to select name of any organization that already exists on Participedia. For new organizations, first publish this case to save your work then publish a new organization. To add your new organization, return to edit this case.',
  'Provide information about additional organizers and sponsors of the initiative in the "Originating Entities and Funding" section of the case narrative.',
  'Type to search & generate possible database matches',
  'Type of Organizer/Manager',
  'Select up to three types of organizers or managers.',
  '',
  'Select up to 3 types of organizers or managers',
  'Funder',
  'Who funded this case of public participation? Provide names of the organizations, government agencies, or individuals who paid for this initiative.',
  'Provide additional information about funders of the initiative in the "Originating Entities and Funding" section of the case narrative.',
  'Who funded this case?',
  'Types of Funder',
  'null',
  '',
  'null',
  'Staff',
  'Were any paid staff or consultants involved in this case?',
  '',
  'Were paid staff or consultants involved?',
  'Volunteers',
  'Did unpaid volunteers help implement this case?',
  '',
  'Were unpaid volunteers involved?',
  'Evidence of Impact',
  'Did this initiative contribute to social and/or political change?',
  '',
  'Did this work contribute to social or political change?',
  'Types of Change',
  'Select and rank up to five types of change to which this case contributed, in order of relevance, with "1" being the most relevant type of change.',
  'Provide additional detail in the "Influence, Outcomes, and Effects" section of the case narrative.',
  'Select & rank up to 5 types of change to which this case contributed',
  'Implementers of Change',
  'Select up to three types of actors who played roles in implementing ideas that emerged from this initiative.',
  '',
  'Select & rank up to 3 types of implementers of change',
  'Formal Evaluation',
  'Was a formal evaluation of this initiative conducted?',
  '',
  'Was there a formal evaluation of this case?',
  'Evaluation Report Document',
  'Upload evaluation report from your device.',
  '',
  'Upload relevant documents',
  'Evaluation Report Link',
  'Provide a link to the evaluation report here.',
  '',
  'Add a link'
);

INSERT INTO sections_static_localized VALUES (
  'en',
  'Quick Submit',
  'Overview',
  'Location',
  'Media',
  'Date & Duration',
  'Purpose & Approach',
  'Participants',
  'Process',
  'Organizers',
  'Resources',
  'Evidence of Impact'
);
