CREATE TABLE case_edit_localized (
  language TEXT DEFAULT 'Localized language',
  quick_submit_sectionlabel TEXT DEFAULT 'Localized quick_submit_sectionlabel',
  overview_sectionlabel TEXT DEFAULT 'Localized overview_sectionlabel',
  location_sectionlabel TEXT DEFAULT 'Localized location_sectionlabel',
  media_sectionlabel TEXT DEFAULT 'Localized media_sectionlabel',
  date_sectionlabel TEXT DEFAULT 'Localized date_sectionlabel',
  purpose_sectionlabel TEXT DEFAULT 'Localized purpose_sectionlabel',
  participants_sectionlabel TEXT DEFAULT 'Localized participants_sectionlabel',
  process_sectionlabel TEXT DEFAULT 'Localized process_sectionlabel',
  organizers_sectionlabel TEXT DEFAULT 'Localized organizers_sectionlabel',
  resources_sectionlabel TEXT DEFAULT 'Localized resources_sectionlabel',
  evidence_sectionlabel TEXT DEFAULT 'Localized evidence_sectionlabel',
  title_label TEXT DEFAULT 'Localized title_label',
  title_instructional TEXT DEFAULT 'Localized title_instructional',
  title_info TEXT DEFAULT 'Localized title_info',
  title_placeholder TEXT DEFAULT 'Localized title_placeholder',
  general_issues_label TEXT DEFAULT 'Localized general_issues_label',
  general_issues_instructional TEXT DEFAULT 'Localized general_issues_instructional',
  general_issues_info TEXT DEFAULT 'Localized general_issues_info',
  general_issues_placeholder TEXT DEFAULT 'Localized general_issues_placeholder',
  brief_description_label TEXT DEFAULT 'Localized brief_description_label',
  brief_description_instructional TEXT DEFAULT 'Localized brief_description_instructional',
  brief_description_info TEXT DEFAULT 'Localized brief_description_info',
  brief_description_placeholder TEXT DEFAULT 'Localized brief_description_placeholder',
  body_label TEXT DEFAULT 'Localized body_label',
  body_instructional TEXT DEFAULT 'Localized body_instructional',
  body_info TEXT DEFAULT 'Localized body_info',
  body_placeholder TEXT DEFAULT 'Localized body_placeholder',
  tags_label TEXT DEFAULT 'Localized tags_label',
  tags_instructional TEXT DEFAULT 'Localized tags_instructional',
  tags_info TEXT DEFAULT 'Localized tags_info',
  tags_placeholder TEXT DEFAULT 'Localized tags_placeholder',
  location_label TEXT DEFAULT 'Localized location_label',
  location_instructional TEXT DEFAULT 'Localized location_instructional',
  location_info TEXT DEFAULT 'Localized location_info',
  location_placeholder TEXT DEFAULT 'Localized location_placeholder',
  scope_label TEXT DEFAULT 'Localized scope_label',
  scope_instructional TEXT DEFAULT 'Localized scope_instructional',
  scope_info TEXT DEFAULT 'Localized scope_info',
  scope_placeholder TEXT DEFAULT 'Localized scope_placeholder',
  scope_value_organization TEXT DEFAULT 'Localized scope_value_organization',
  scope_value_neighbourhood TEXT DEFAULT 'Localized scope_value_neighbourhood',
  scope_value_city TEXT DEFAULT 'Localized scope_value_city',
  scope_value_metropolitan TEXT DEFAULT 'Localized scope_value_metropolitan',
  scope_value_regional TEXT DEFAULT 'Localized scope_value_regional',
  scope_value_national TEXT DEFAULT 'Localized scope_value_national',
  scope_value_multinational TEXT DEFAULT 'Localized scope_value_multinational',
  scope_value_no_limit TEXT DEFAULT 'Localized scope_value_no_limit',
  has_components_label TEXT DEFAULT 'Localized has_components_label',
  has_components_instructional TEXT DEFAULT 'Localized has_components_instructional',
  has_components_info TEXT DEFAULT 'Localized has_components_info',
  has_components_placeholder TEXT DEFAULT 'Localized has_components_placeholder',
  is_component_of_label TEXT DEFAULT 'Localized is_component_of_label',
  is_component_of_instructional TEXT DEFAULT 'Localized is_component_of_instructional',
  is_component_of_info TEXT DEFAULT 'Localized is_component_of_info',
  is_component_of_placeholder TEXT DEFAULT 'Localized is_component_of_placeholder',
  file_upload_label TEXT DEFAULT 'Localized file_upload_label',
  file_upload_instructional TEXT DEFAULT 'Localized file_upload_instructional',
  file_upload_info TEXT DEFAULT 'Localized file_upload_info',
  file_upload_placeholder TEXT DEFAULT 'Localized file_upload_placeholder',
  file_link_label TEXT DEFAULT 'Localized file_link_label',
  file_link_instructional TEXT DEFAULT 'Localized file_link_instructional',
  file_link_info TEXT DEFAULT 'Localized file_link_info',
  file_link_placeholder TEXT DEFAULT 'Localized file_link_placeholder',
  file_attribution_label TEXT DEFAULT 'Localized file_attribution_label',
  file_attribution_instructional TEXT DEFAULT 'Localized file_attribution_instructional',
  file_attribution_info TEXT DEFAULT 'Localized file_attribution_info',
  file_attribution_placeholder TEXT DEFAULT 'Localized file_attribution_placeholder',
  file_title_label TEXT DEFAULT 'Localized file_title_label',
  file_title_instructional TEXT DEFAULT 'Localized file_title_instructional',
  file_title_info TEXT DEFAULT 'Localized file_title_info',
  file_title_placeholder TEXT DEFAULT 'Localized file_title_placeholder',
  link_label TEXT DEFAULT 'Localized link_label',
  link_instructional TEXT DEFAULT 'Localized link_instructional',
  link_info TEXT DEFAULT 'Localized link_info',
  link_placeholder TEXT DEFAULT 'Localized link_placeholder',
  link_attribution_label TEXT DEFAULT 'Localized link_attribution_label',
  link_attribution_instructional TEXT DEFAULT 'Localized link_attribution_instructional',
  link_attribution_info TEXT DEFAULT 'Localized link_attribution_info',
  link_attribution_placeholder TEXT DEFAULT 'Localized link_attribution_placeholder',
  link_title_label TEXT DEFAULT 'Localized link_title_label',
  link_title_instructional TEXT DEFAULT 'Localized link_title_instructional',
  link_title_info TEXT DEFAULT 'Localized link_title_info',
  link_title_placeholder TEXT DEFAULT 'Localized link_title_placeholder',
  photo_upload_label TEXT DEFAULT 'Localized photo_upload_label',
  photo_upload_instructional TEXT DEFAULT 'Localized photo_upload_instructional',
  photo_upload_info TEXT DEFAULT 'Localized photo_upload_info',
  photo_upload_placeholder TEXT DEFAULT 'Localized photo_upload_placeholder',
  photo_link_label TEXT DEFAULT 'Localized photo_link_label',
  photo_link_instructional TEXT DEFAULT 'Localized photo_link_instructional',
  photo_link_info TEXT DEFAULT 'Localized photo_link_info',
  photo_link_placeholder TEXT DEFAULT 'Localized photo_link_placeholder',
  photo_attribution_label TEXT DEFAULT 'Localized photo_attribution_label',
  photo_attribution_instructional TEXT DEFAULT 'Localized photo_attribution_instructional',
  photo_attribution_info TEXT DEFAULT 'Localized photo_attribution_info',
  photo_attribution_placeholder TEXT DEFAULT 'Localized photo_attribution_placeholder',
  photo_title_label TEXT DEFAULT 'Localized photo_title_label',
  photo_title_instructional TEXT DEFAULT 'Localized photo_title_instructional',
  photo_title_info TEXT DEFAULT 'Localized photo_title_info',
  photo_title_placeholder TEXT DEFAULT 'Localized photo_title_placeholder',
  video_link_label TEXT DEFAULT 'Localized video_link_label',
  video_link_instructional TEXT DEFAULT 'Localized video_link_instructional',
  video_link_info TEXT DEFAULT 'Localized video_link_info',
  video_link_placeholder TEXT DEFAULT 'Localized video_link_placeholder',
  video_attribution_label TEXT DEFAULT 'Localized video_attribution_label',
  video_attribution_instructional TEXT DEFAULT 'Localized video_attribution_instructional',
  video_attribution_info TEXT DEFAULT 'Localized video_attribution_info',
  video_attribution_placeholder TEXT DEFAULT 'Localized video_attribution_placeholder',
  video_title_label TEXT DEFAULT 'Localized video_title_label',
  video_title_instructional TEXT DEFAULT 'Localized video_title_instructional',
  video_title_info TEXT DEFAULT 'Localized video_title_info',
  video_title_placeholder TEXT DEFAULT 'Localized video_title_placeholder',
  audio_link_label TEXT DEFAULT 'Localized audio_link_label',
  audio_link_instructional TEXT DEFAULT 'Localized audio_link_instructional',
  audio_link_info TEXT DEFAULT 'Localized audio_link_info',
  audio_link_placeholder TEXT DEFAULT 'Localized audio_link_placeholder',
  audio_attribution_label TEXT DEFAULT 'Localized audio_attribution_label',
  audio_attribution_instructional TEXT DEFAULT 'Localized audio_attribution_instructional',
  audio_attribution_info TEXT DEFAULT 'Localized audio_attribution_info',
  audio_attribution_placeholder TEXT DEFAULT 'Localized audio_attribution_placeholder',
  audio_title_label TEXT DEFAULT 'Localized audio_title_label',
  audio_title_instructional TEXT DEFAULT 'Localized audio_title_instructional',
  audio_title_info TEXT DEFAULT 'Localized audio_title_info',
  audio_title_placeholder TEXT DEFAULT 'Localized audio_title_placeholder',
  start_date_label TEXT DEFAULT 'Localized start_date_label',
  start_date_instructional TEXT DEFAULT 'Localized start_date_instructional',
  start_date_info TEXT DEFAULT 'Localized start_date_info',
  start_date_placeholder TEXT DEFAULT 'Localized start_date_placeholder',
  end_date_label TEXT DEFAULT 'Localized end_date_label',
  end_date_instructional TEXT DEFAULT 'Localized end_date_instructional',
  end_date_info TEXT DEFAULT 'Localized end_date_info',
  end_date_placeholder TEXT DEFAULT 'Localized end_date_placeholder',
  ongoing_label TEXT DEFAULT 'Localized ongoing_label',
  ongoing_instructional TEXT DEFAULT 'Localized ongoing_instructional',
  ongoing_info TEXT DEFAULT 'Localized ongoing_info',
  ongoing_placeholder TEXT DEFAULT 'Localized ongoing_placeholder',
  time_limited_label TEXT DEFAULT 'Localized time_limited_label',
  time_limited_instructional TEXT DEFAULT 'Localized time_limited_instructional',
  time_limited_info TEXT DEFAULT 'Localized time_limited_info',
  time_limited_placeholder TEXT DEFAULT 'Localized time_limited_placeholder',
  time_limited_value_single TEXT DEFAULT 'Localized time_limited_value_single',
  time_limited_value_repeated TEXT DEFAULT 'Localized time_limited_value_repeated',
  purpose_label TEXT DEFAULT 'Localized purpose_label',
  purpose_instructional TEXT DEFAULT 'Localized purpose_instructional',
  purpose_info TEXT DEFAULT 'Localized purpose_info',
  purpose_placeholder TEXT DEFAULT 'Localized purpose_placeholder',
  purpose_value_public TEXT DEFAULT 'Localized purpose_value_public',
  purpose_value_private TEXT DEFAULT 'Localized purpose_value_private',
  purpose_value_goods TEXT DEFAULT 'Localized purpose_value_goods',
  purpose_value_civic TEXT DEFAULT 'Localized purpose_value_civic',
  purpose_value_research TEXT DEFAULT 'Localized purpose_value_research',
  approach_label TEXT DEFAULT 'Localized approach_label',
  approach_instructional TEXT DEFAULT 'Localized approach_instructional',
  approach_info TEXT DEFAULT 'Localized approach_info',
  approach_placeholder TEXT DEFAULT 'Localized approach_placeholder',
  approach_value_advocacy TEXT DEFAULT 'Localized approach_value_advocacy',
  approach_value_citizenship TEXT DEFAULT 'Localized approach_value_citizenship',
  approach_value_civil TEXT DEFAULT 'Localized approach_value_civil',
  approach_value_cogovernance TEXT DEFAULT 'Localized approach_value_cogovernance',
  approach_value_public_partner TEXT DEFAULT 'Localized approach_value_public_partner',
  approach_value_private_partner TEXT DEFAULT 'Localized approach_value_private_partner',
  approach_value_consultation TEXT DEFAULT 'Localized approach_value_consultation',
  approach_value_decision TEXT DEFAULT 'Localized approach_value_decision',
  approach_value_independent TEXT DEFAULT 'Localized approach_value_independent',
  approach_value_nongovernmental TEXT DEFAULT 'Localized approach_value_nongovernmental',
  approach_value_political TEXT DEFAULT 'Localized approach_value_political',
  approach_value_leadership TEXT DEFAULT 'Localized approach_value_leadership',
  approach_value_auditing TEXT DEFAULT 'Localized approach_value_auditing',
  approach_value_protest TEXT DEFAULT 'Localized approach_value_protest',
  approach_value_research TEXT DEFAULT 'Localized approach_value_research',
  approach_value_mobilization TEXT DEFAULT 'Localized approach_value_mobilization',
  public_spectrum_label TEXT DEFAULT 'Localized public_spectrum_label',
  public_spectrum_instructional TEXT DEFAULT 'Localized public_spectrum_instructional',
  public_spectrum_info TEXT DEFAULT 'Localized public_spectrum_info',
  public_spectrum_placeholder TEXT DEFAULT 'Localized public_spectrum_placeholder',
  public_spectrum_value_inform TEXT DEFAULT 'Localized public_spectrum_value_inform',
  public_spectrum_value_consult TEXT DEFAULT 'Localized public_spectrum_value_consult',
  public_spectrum_value_involve TEXT DEFAULT 'Localized public_spectrum_value_involve',
  public_spectrum_value_collaborate TEXT DEFAULT 'Localized public_spectrum_value_collaborate',
  public_spectrum_value_empower TEXT DEFAULT 'Localized public_spectrum_value_empower',
  public_spectrum_value_na TEXT DEFAULT 'Localized public_spectrum_value_na',
  number_of_participants_label TEXT DEFAULT 'Localized number_of_participants_label',
  number_of_participants_instructional TEXT DEFAULT 'Localized number_of_participants_instructional',
  number_of_participants_info TEXT DEFAULT 'Localized number_of_participants_info',
  number_of_participants_placeholder TEXT DEFAULT 'Localized number_of_participants_placeholder',
  open_limited_label TEXT DEFAULT 'Localized open_limited_label',
  open_limited_instructional TEXT DEFAULT 'Localized open_limited_instructional',
  open_limited_info TEXT DEFAULT 'Localized open_limited_info',
  open_limited_placeholder TEXT DEFAULT 'Localized open_limited_placeholder',
  open_limited_value_all TEXT DEFAULT 'Localized open_limited_value_all',
  open_limited_value_special TEXT DEFAULT 'Localized open_limited_value_special',
  open_limited_value_limited TEXT DEFAULT 'Localized open_limited_value_limited',
  open_limited_value_both TEXT DEFAULT 'Localized open_limited_value_both',
  recruitment_method_label TEXT DEFAULT 'Localized recruitment_method_label',
  recruitment_method_instructional TEXT DEFAULT 'Localized recruitment_method_instructional',
  recruitment_method_info TEXT DEFAULT 'Localized recruitment_method_info',
  recruitment_method_placeholder TEXT DEFAULT 'Localized recruitment_method_placeholder',
  recruitment_method_value_captive TEXT DEFAULT 'Localized recruitment_method_value_captive',
  recruitment_method_value_random TEXT DEFAULT 'Localized recruitment_method_value_random',
  recruitment_method_value_stratified TEXT DEFAULT 'Localized recruitment_method_value_stratified',
  recruitment_method_value_appointment TEXT DEFAULT 'Localized recruitment_method_value_appointment',
  recruitment_method_value_election TEXT DEFAULT 'Localized recruitment_method_value_election',
  recruitment_method_value_na TEXT DEFAULT 'Localized recruitment_method_value_na',
  targeted_participants_label TEXT DEFAULT 'Localized targeted_participants_label',
  targeted_participants_instructional TEXT DEFAULT 'Localized targeted_participants_instructional',
  targeted_participants_info TEXT DEFAULT 'Localized targeted_participants_info',
  targeted_participants_placeholder TEXT DEFAULT 'Localized targeted_participants_placeholder',
  targeted_participants_value_appointed TEXT DEFAULT 'Localized targeted_participants_value_appointed',
  targeted_participants_value_lgbt TEXT DEFAULT 'Localized targeted_participants_value_lgbt',
  targeted_participants_value_elderly TEXT DEFAULT 'Localized targeted_participants_value_elderly',
  targeted_participants_value_elected TEXT DEFAULT 'Localized targeted_participants_value_elected',
  targeted_participants_value_experts TEXT DEFAULT 'Localized targeted_participants_value_experts',
  targeted_participants_value_indigenous TEXT DEFAULT 'Localized targeted_participants_value_indigenous',
  targeted_participants_value_immigrants TEXT DEFAULT 'Localized targeted_participants_value_immigrants',
  targeted_participants_value_low_income TEXT DEFAULT 'Localized targeted_participants_value_low_income',
  targeted_participants_value_men TEXT DEFAULT 'Localized targeted_participants_value_men',
  targeted_participants_value_disabilities TEXT DEFAULT 'Localized targeted_participants_value_disabilities',
  targeted_participants_value_ethnic TEXT DEFAULT 'Localized targeted_participants_value_ethnic',
  targeted_participants_value_religious TEXT DEFAULT 'Localized targeted_participants_value_religious',
  targeted_participants_value_stakeholders TEXT DEFAULT 'Localized targeted_participants_value_stakeholders',
  targeted_participants_value_students TEXT DEFAULT 'Localized targeted_participants_value_students',
  targeted_participants_value_women TEXT DEFAULT 'Localized targeted_participants_value_women',
  targeted_participants_value_youth TEXT DEFAULT 'Localized targeted_participants_value_youth',
  method_types_label TEXT DEFAULT 'Localized method_types_label',
  method_types_instructional TEXT DEFAULT 'Localized method_types_instructional',
  method_types_info TEXT DEFAULT 'Localized method_types_info',
  method_types_placeholder TEXT DEFAULT 'Localized method_types_placeholder',
  method_types_value_ TEXT DEFAULT 'Localized method_types_value_',
  method_types_value_community TEXT DEFAULT 'Localized method_types_value_community',
  method_types_value_deliberative TEXT DEFAULT 'Localized method_types_value_deliberative',
  method_types_value_democracy TEXT DEFAULT 'Localized method_types_value_democracy',
  method_types_value_auditing TEXT DEFAULT 'Localized method_types_value_auditing',
  method_types_value_education TEXT DEFAULT 'Localized method_types_value_education',
  method_types_value_conversation TEXT DEFAULT 'Localized method_types_value_conversation',
  method_types_value_participation TEXT DEFAULT 'Localized method_types_value_participation',
  method_types_value_management TEXT DEFAULT 'Localized method_types_value_management',
  method_types_value_civic TEXT DEFAULT 'Localized method_types_value_civic',
  method_types_value_participant_meetings TEXT DEFAULT 'Localized method_types_value_participant_meetings',
  method_types_value_arts TEXT DEFAULT 'Localized method_types_value_arts',
  method_types_value_planning TEXT DEFAULT 'Localized method_types_value_planning',
  method_types_value_protest TEXT DEFAULT 'Localized method_types_value_protest',
  method_types_value_budgeting TEXT DEFAULT 'Localized method_types_value_budgeting',
  method_types_value_public_meetings TEXT DEFAULT 'Localized method_types_value_public_meetings',
  method_types_value_research TEXT DEFAULT 'Localized method_types_value_research',
  tool_types_label TEXT DEFAULT 'Localized tool_types_label',
  tool_types_instructional TEXT DEFAULT 'Localized tool_types_instructional',
  tool_types_info TEXT DEFAULT 'Localized tool_types_info',
  tool_types_placeholder TEXT DEFAULT 'Localized tool_types_placeholder',
  tool_types_value_money TEXT DEFAULT 'Localized tool_types_value_money',
  tool_types_value_feedback TEXT DEFAULT 'Localized tool_types_value_feedback',
  tool_types_value_dialogue TEXT DEFAULT 'Localized tool_types_value_dialogue',
  tool_types_value_decisions TEXT DEFAULT 'Localized tool_types_value_decisions',
  tool_types_value_legislation TEXT DEFAULT 'Localized tool_types_value_legislation',
  tool_types_value_recruit TEXT DEFAULT 'Localized tool_types_value_recruit',
  tool_types_value_map TEXT DEFAULT 'Localized tool_types_value_map',
  tool_types_value_policies TEXT DEFAULT 'Localized tool_types_value_policies',
  tool_types_value_educate TEXT DEFAULT 'Localized tool_types_value_educate',
  specific_tools_label TEXT DEFAULT 'Localized specific_tools_label',
  specific_tools_instructional TEXT DEFAULT 'Localized specific_tools_instructional',
  specific_tools_info TEXT DEFAULT 'Localized specific_tools_info',
  specific_tools_placeholder TEXT DEFAULT 'Localized specific_tools_placeholder',
  legality_label TEXT DEFAULT 'Localized legality_label',
  legality_instructional TEXT DEFAULT 'Localized legality_instructional',
  legality_info TEXT DEFAULT 'Localized legality_info',
  legality_placeholder TEXT DEFAULT 'Localized legality_placeholder',
  legality_value_yes TEXT DEFAULT 'Localized legality_value_yes',
  legality_value_no TEXT DEFAULT 'Localized legality_value_no',
  legality_value_idk TEXT DEFAULT 'Localized legality_value_idk',
  facilitators_label TEXT DEFAULT 'Localized facilitators_label',
  facilitators_instructional TEXT DEFAULT 'Localized facilitators_instructional',
  facilitators_info TEXT DEFAULT 'Localized facilitators_info',
  facilitators_placeholder TEXT DEFAULT 'Localized facilitators_placeholder',
  facilitators_value_yes TEXT DEFAULT 'Localized facilitators_value_yes',
  facilitators_value_no TEXT DEFAULT 'Localized facilitators_value_no',
  facilitators_value_na TEXT DEFAULT 'Localized facilitators_value_na',
  facilitator_training_label TEXT DEFAULT 'Localized facilitator_training_label',
  facilitator_training_instructional TEXT DEFAULT 'Localized facilitator_training_instructional',
  facilitator_training_info TEXT DEFAULT 'Localized facilitator_training_info',
  facilitator_training_placeholder TEXT DEFAULT 'Localized facilitator_training_placeholder',
  facilitator_training_value_professional TEXT DEFAULT 'Localized facilitator_training_value_professional',
  facilitator_training_value_trained TEXT DEFAULT 'Localized facilitator_training_value_trained',
  facilitator_training_value_untrained TEXT DEFAULT 'Localized facilitator_training_value_untrained',
  facetoface_label TEXT DEFAULT 'Localized facetoface_label',
  facetoface_instructional TEXT DEFAULT 'Localized facetoface_instructional',
  facetoface_info TEXT DEFAULT 'Localized facetoface_info',
  facetoface_placeholder TEXT DEFAULT 'Localized facetoface_placeholder',
  facetoface_value_facetoface TEXT DEFAULT 'Localized facetoface_value_facetoface',
  facetoface_value_online TEXT DEFAULT 'Localized facetoface_value_online',
  facetoface_value_both TEXT DEFAULT 'Localized facetoface_value_both',
  participants_interaction_label TEXT DEFAULT 'Localized participants_interaction_label',
  participants_interaction_instructional TEXT DEFAULT 'Localized participants_interaction_instructional',
  participants_interaction_info TEXT DEFAULT 'Localized participants_interaction_info',
  participants_interaction_placeholder TEXT DEFAULT 'Localized participants_interaction_placeholder',
  participants_interaction_value_drama TEXT DEFAULT 'Localized participants_interaction_value_drama',
  participants_interaction_value_questions TEXT DEFAULT 'Localized participants_interaction_value_questions',
  participants_interaction_value_dialogue TEXT DEFAULT 'Localized participants_interaction_value_dialogue',
  participants_interaction_value_opinions TEXT DEFAULT 'Localized participants_interaction_value_opinions',
  participants_interaction_value_testimony TEXT DEFAULT 'Localized participants_interaction_value_testimony',
  participants_interaction_value_social TEXT DEFAULT 'Localized participants_interaction_value_social',
  participants_interaction_value_spectator TEXT DEFAULT 'Localized participants_interaction_value_spectator',
  participants_interaction_value_bargaining TEXT DEFAULT 'Localized participants_interaction_value_bargaining',
  participants_interaction_value_storytelling TEXT DEFAULT 'Localized participants_interaction_value_storytelling',
  participants_interaction_value_teaching TEXT DEFAULT 'Localized participants_interaction_value_teaching',
  participants_interaction_value_none TEXT DEFAULT 'Localized participants_interaction_value_none',
  learning_resources_label TEXT DEFAULT 'Localized learning_resources_label',
  learning_resources_instructional TEXT DEFAULT 'Localized learning_resources_instructional',
  learning_resources_info TEXT DEFAULT 'Localized learning_resources_info',
  learning_resources_placeholder TEXT DEFAULT 'Localized learning_resources_placeholder',
  learning_resources_value_expert TEXT DEFAULT 'Localized learning_resources_value_expert',
  learning_resources_value_participant TEXT DEFAULT 'Localized learning_resources_value_participant',
  learning_resources_value_visits TEXT DEFAULT 'Localized learning_resources_value_visits',
  learning_resources_value_teach TEXT DEFAULT 'Localized learning_resources_value_teach',
  learning_resources_value_video TEXT DEFAULT 'Localized learning_resources_value_video',
  learning_resources_value_written TEXT DEFAULT 'Localized learning_resources_value_written',
  learning_resources_value_none TEXT DEFAULT 'Localized learning_resources_value_none',
  learning_resources_value_na TEXT DEFAULT 'Localized learning_resources_value_na',
  decision_methods_label TEXT DEFAULT 'Localized decision_methods_label',
  decision_methods_instructional TEXT DEFAULT 'Localized decision_methods_instructional',
  decision_methods_info TEXT DEFAULT 'Localized decision_methods_info',
  decision_methods_placeholder TEXT DEFAULT 'Localized decision_methods_placeholder',
  decision_methods_value_opinion TEXT DEFAULT 'Localized decision_methods_value_opinion',
  decision_methods_value_ideas TEXT DEFAULT 'Localized decision_methods_value_ideas',
  decision_methods_value_agreement TEXT DEFAULT 'Localized decision_methods_value_agreement',
  decision_methods_value_voting TEXT DEFAULT 'Localized decision_methods_value_voting',
  decision_methods_value_na TEXT DEFAULT 'Localized decision_methods_value_na',
  decision_methods_value_idk TEXT DEFAULT 'Localized decision_methods_value_idk',
  if_voting_label TEXT DEFAULT 'Localized if_voting_label',
  if_voting_instructional TEXT DEFAULT 'Localized if_voting_instructional',
  if_voting_info TEXT DEFAULT 'Localized if_voting_info',
  if_voting_placeholder TEXT DEFAULT 'Localized if_voting_placeholder',
  if_voting_value_preferential TEXT DEFAULT 'Localized if_voting_value_preferential',
  if_voting_value_plurality TEXT DEFAULT 'Localized if_voting_value_plurality',
  if_voting_value_majoritarian TEXT DEFAULT 'Localized if_voting_value_majoritarian',
  if_voting_value_super TEXT DEFAULT 'Localized if_voting_value_super',
  if_voting_value_unanimous TEXT DEFAULT 'Localized if_voting_value_unanimous',
  if_voting_value_dk TEXT DEFAULT 'Localized if_voting_value_dk',
  insights_outcomes_label TEXT DEFAULT 'Localized insights_outcomes_label',
  insights_outcomes_instructional TEXT DEFAULT 'Localized insights_outcomes_instructional',
  insights_outcomes_info TEXT DEFAULT 'Localized insights_outcomes_info',
  insights_outcomes_placeholder TEXT DEFAULT 'Localized insights_outcomes_placeholder',
  insights_outcomes_value_artistic TEXT DEFAULT 'Localized insights_outcomes_value_artistic',
  insights_outcomes_value_media TEXT DEFAULT 'Localized insights_outcomes_value_media',
  insights_outcomes_value_social TEXT DEFAULT 'Localized insights_outcomes_value_social',
  insights_outcomes_value_independent TEXT DEFAULT 'Localized insights_outcomes_value_independent',
  insights_outcomes_value_report TEXT DEFAULT 'Localized insights_outcomes_value_report',
  insights_outcomes_value_minority TEXT DEFAULT 'Localized insights_outcomes_value_minority',
  insights_outcomes_value_petitions TEXT DEFAULT 'Localized insights_outcomes_value_petitions',
  insights_outcomes_value_protests TEXT DEFAULT 'Localized insights_outcomes_value_protests',
  insights_outcomes_value_hearings TEXT DEFAULT 'Localized insights_outcomes_value_hearings',
  insights_outcomes_value_wordofmouth TEXT DEFAULT 'Localized insights_outcomes_value_wordofmouth',
  insights_outcomes_value_na TEXT DEFAULT 'Localized insights_outcomes_value_na',
  primary_organizer_label TEXT DEFAULT 'Localized primary_organizer_label',
  primary_organizer_instructional TEXT DEFAULT 'Localized primary_organizer_instructional',
  primary_organizer_info TEXT DEFAULT 'Localized primary_organizer_info',
  primary_organizer_placeholder TEXT DEFAULT 'Localized primary_organizer_placeholder',
  organizer_type_label TEXT DEFAULT 'Localized organizer_type_label',
  organizer_type_instructional TEXT DEFAULT 'Localized organizer_type_instructional',
  organizer_type_info TEXT DEFAULT 'Localized organizer_type_info',
  organizer_type_placeholder TEXT DEFAULT 'Localized organizer_type_placeholder',
  organizer_type_value_academic TEXT DEFAULT 'Localized organizer_type_value_academic',
  organizer_type_value_activist TEXT DEFAULT 'Localized organizer_type_value_activist',
  organizer_type_value_community TEXT DEFAULT 'Localized organizer_type_value_community',
  organizer_type_value_faith TEXT DEFAULT 'Localized organizer_type_value_faith',
  organizer_type_value_business TEXT DEFAULT 'Localized organizer_type_value_business',
  organizer_type_value_government_corp TEXT DEFAULT 'Localized organizer_type_value_government_corp',
  organizer_type_value_individual TEXT DEFAULT 'Localized organizer_type_value_individual',
  organizer_type_value_international TEXT DEFAULT 'Localized organizer_type_value_international',
  organizer_type_value_local_government TEXT DEFAULT 'Localized organizer_type_value_local_government',
  organizer_type_value_national_government TEXT DEFAULT 'Localized organizer_type_value_national_government',
  organizer_type_value_ngo TEXT DEFAULT 'Localized organizer_type_value_ngo',
  organizer_type_value_philanthropic TEXT DEFAULT 'Localized organizer_type_value_philanthropic',
  organizer_type_value_regional_government TEXT DEFAULT 'Localized organizer_type_value_regional_government',
  organizer_type_value_social TEXT DEFAULT 'Localized organizer_type_value_social',
  organizer_type_value_labour TEXT DEFAULT 'Localized organizer_type_value_labour',
  organizer_type_value_na TEXT DEFAULT 'Localized organizer_type_value_na',
  funder_label TEXT DEFAULT 'Localized funder_label',
  funder_instructional TEXT DEFAULT 'Localized funder_instructional',
  funder_info TEXT DEFAULT 'Localized funder_info',
  funder_placeholder TEXT DEFAULT 'Localized funder_placeholder',
  funder_types_label TEXT DEFAULT 'Localized funder_types_label',
  funder_types_instructional TEXT DEFAULT 'Localized funder_types_instructional',
  funder_types_info TEXT DEFAULT 'Localized funder_types_info',
  funder_types_placeholder TEXT DEFAULT 'Localized funder_types_placeholder',
  funder_types_value_academic TEXT DEFAULT 'Localized funder_types_value_academic',
  funder_types_value_activist TEXT DEFAULT 'Localized funder_types_value_activist',
  funder_types_value_community TEXT DEFAULT 'Localized funder_types_value_community',
  funder_types_value_faith TEXT DEFAULT 'Localized funder_types_value_faith',
  funder_types_value_business TEXT DEFAULT 'Localized funder_types_value_business',
  funder_types_value_government_corp TEXT DEFAULT 'Localized funder_types_value_government_corp',
  funder_types_value_individual TEXT DEFAULT 'Localized funder_types_value_individual',
  funder_types_value_international TEXT DEFAULT 'Localized funder_types_value_international',
  funder_types_value_local_government TEXT DEFAULT 'Localized funder_types_value_local_government',
  funder_types_value_national_government TEXT DEFAULT 'Localized funder_types_value_national_government',
  funder_types_value_ngo TEXT DEFAULT 'Localized funder_types_value_ngo',
  funder_types_value_philanthropic TEXT DEFAULT 'Localized funder_types_value_philanthropic',
  funder_types_value_regional_government TEXT DEFAULT 'Localized funder_types_value_regional_government',
  funder_types_value_social TEXT DEFAULT 'Localized funder_types_value_social',
  funder_types_value_labour TEXT DEFAULT 'Localized funder_types_value_labour',
  funder_types_value_na TEXT DEFAULT 'Localized funder_types_value_na',
  staff_label TEXT DEFAULT 'Localized staff_label',
  staff_instructional TEXT DEFAULT 'Localized staff_instructional',
  staff_info TEXT DEFAULT 'Localized staff_info',
  staff_placeholder TEXT DEFAULT 'Localized staff_placeholder',
  volunteers_label TEXT DEFAULT 'Localized volunteers_label',
  volunteers_instructional TEXT DEFAULT 'Localized volunteers_instructional',
  volunteers_info TEXT DEFAULT 'Localized volunteers_info',
  volunteers_placeholder TEXT DEFAULT 'Localized volunteers_placeholder',
  impact_evidence_label TEXT DEFAULT 'Localized impact_evidence_label',
  impact_evidence_instructional TEXT DEFAULT 'Localized impact_evidence_instructional',
  impact_evidence_info TEXT DEFAULT 'Localized impact_evidence_info',
  impact_evidence_placeholder TEXT DEFAULT 'Localized impact_evidence_placeholder',
  change_types_label TEXT DEFAULT 'Localized change_types_label',
  change_types_instructional TEXT DEFAULT 'Localized change_types_instructional',
  change_types_info TEXT DEFAULT 'Localized change_types_info',
  change_types_placeholder TEXT DEFAULT 'Localized change_types_placeholder',
  change_types_value_behaviour TEXT DEFAULT 'Localized change_types_value_behaviour',
  change_types_value_capacities TEXT DEFAULT 'Localized change_types_value_capacities',
  change_types_value_policy TEXT DEFAULT 'Localized change_types_value_policy',
  change_types_value_operations TEXT DEFAULT 'Localized change_types_value_operations',
  change_types_value_transformation TEXT DEFAULT 'Localized change_types_value_transformation',
  implementers_of_change_label TEXT DEFAULT 'Localized implementers_of_change_label',
  implementers_of_change_instructional TEXT DEFAULT 'Localized implementers_of_change_instructional',
  implementers_of_change_info TEXT DEFAULT 'Localized implementers_of_change_info',
  implementers_of_change_placeholder TEXT DEFAULT 'Localized implementers_of_change_placeholder',
  implementers_of_change_value_public TEXT DEFAULT 'Localized implementers_of_change_value_public',
  implementers_of_change_value_stakeholders TEXT DEFAULT 'Localized implementers_of_change_value_stakeholders',
  implementers_of_change_value_elected TEXT DEFAULT 'Localized implementers_of_change_value_elected',
  implementers_of_change_value_appointed TEXT DEFAULT 'Localized implementers_of_change_value_appointed',
  implementers_of_change_value_experts TEXT DEFAULT 'Localized implementers_of_change_value_experts',
  implementers_of_change_value_corporations TEXT DEFAULT 'Localized implementers_of_change_value_corporations',
  implementers_of_change_value_idk TEXT DEFAULT 'Localized implementers_of_change_value_idk',
  formal_evaluation_label TEXT DEFAULT 'Localized formal_evaluation_label',
  formal_evaluation_instructional TEXT DEFAULT 'Localized formal_evaluation_instructional',
  formal_evaluation_info TEXT DEFAULT 'Localized formal_evaluation_info',
  formal_evaluation_placeholder TEXT DEFAULT 'Localized formal_evaluation_placeholder',
  evaluation_reports_label TEXT DEFAULT 'Localized evaluation_reports_label',
  evaluation_reports_instructional TEXT DEFAULT 'Localized evaluation_reports_instructional',
  evaluation_reports_info TEXT DEFAULT 'Localized evaluation_reports_info',
  evaluation_reports_placeholder TEXT DEFAULT 'Localized evaluation_reports_placeholder',
  evaluation_links_label TEXT DEFAULT 'Localized evaluation_links_label',
  evaluation_links_instructional TEXT DEFAULT 'Localized evaluation_links_instructional',
  evaluation_links_info TEXT DEFAULT 'Localized evaluation_links_info',
  evaluation_links_placeholder TEXT DEFAULT 'Localized evaluation_links_placeholder'
);

INSERT INTO case_edit_localized VALUES (
  'en',
  'Quick Submit',
  'Overview',
  'Location',
  'Media',
  'Date & Duration',
  'Purpose & Approach',
  'Participants',
  'Process',
  'Organizers',
  'Resources',
  'Evidence of Impact',
  'Title of Case',
  'Give this public participation project or event a descriptive title in 10 words or less. For example, “Brazilian Dialogue on Diversity" or "New York City Public Issues Forum."',
  '',
  'Enter title in 10 words or less',
  'General Issues',
  'Rank order up to three of the most relevant issues addressed, with "1" indicating the most relevant issue. You will be asked to provide more detailed information in the Specific Topics field below.',
  '',
  'Select & rank up to 3 issues',
  'Brief Description',
  'Enter tweet-length (280 characters or less) description of this case.',
  '',
  'Enter tweet-length description',
  'Narrative',
  'The following standard structure makes it easier to compare and analyze entries. Please use the headings below and refer to our guidelines as you prepare your case entry.',
  '',
  'Problems and Purpose Background History and Context Organizing, Supporting, and Funding Entities Participant Recruitment and Selection Methods and Tools Used Deliberation, Decisions, and Public Interaction Influence, Outcomes, and Effects Analysis and Lessons Learned See Also References External Links Notes',
  'Tags',
  'Select the tags that best describe this case.',
  '',
  'Enter one or more tags',
  'Primary Location',
  'Type to select an address, city or country where the primary case activities occurred. List any additional locations in the case narrative under "Originating Entities and Funding". You may also want to create separate case components for the locations of other case activities.',
  '',
  'Type to search for a known location',
  'Scope of Influence',
  'Select geographical or jurisdictional scope',
  '',
  'Select geographical or jurisdictional scope',
  'Organization (e.g. a local business or cooperative using participatory methods to manage and govern itself)',
  'Neighbourhood',
  'City/Town',
  'Metropolitan Area',
  'Regional (e.g. State, Province, Autonomous Region)',
  'National',
  'Multinational',
  'No Geographical Limits (e.g. online environment where anyone from any place can take part)',
  'Add Components to this Case',
  'A case can have multiple components, but they must already be published cases on Participedia. Type to search for an existing case in Participedia to label it as a component of this case. Select one or more.',
  'If you cannot find the case you are looking for, first publish this entry to save your work. Next use quick submit to publish the component case entry. Then return to this case entry and add your new case entry as a component.',
  'Search for existing case/component',
  'Make This Case a Component of Another Case',
  'A case can only be a component of one other case, and the other case must already be published on Participedia. Type to search for an existing case in Participedia to label this case as a component of it. Select one.',
  'If you cannot find the case you are looking for, first publish this entry to save your work. Next use quick submit to publish the ‘parent’ case entry. Then return to this case entry and label this case as a component of the new ‘parent’ case.',
  'Search for existing case/parent',
  'Files',
  'Upload relevant documents here. Supported file types include: rtf, txt, doc, docx, xls, xlsx, pdf, ppt, pptx, pps, ppsx, odt, ods and odp.',
  '',
  'Add file',
  'Source Link',
  'If applicable, provide a link to where the original file was sourced.',
  '',
  'Link to Original',
  'Attribution',
  'Who is the original owner or creator of this file?',
  '',
  'Owner or creator',
  'Title or Description',
  'Provide the original title or description of this file in ten words or less.',
  ',',
  'Title or description',
  'Links',
  'If there is a main website for this case, enter it here. Add links to additional sources so that readers and editors can find more information about this case online.',
  '',
  'Add link',
  'Attribution',
  'Who is the original owner or creator of this linked content?',
  '',
  'Owner or creator',
  'Title or Description',
  'Provide the original title or description of this linked content in ten words or less.',
  '',
  'Title or description',
  'Photos',
  'Select a photo from your device',
  '',
  'Select a photo from your device',
  'Source Link',
  'If applicable, provide a link to where the original photo was sourced.',
  '',
  'Link to original',
  'Attribution',
  'Who is the original owner or creator of this photo?',
  '',
  'Owner or creator',
  'Title or Description',
  'Provide the original title or description of this photo in ten words or less.',
  ',',
  'Title or description',
  'Videos',
  'Add a video link from Vimeo or YouTube.',
  '',
  'Add a video link (Vimeo or YouTube)',
  'Attribution',
  'Who is the original owner or creator of this video?',
  '',
  'Owner or creator',
  'Title or Description',
  'Provide the original title or description of this video.',
  '',
  'Title or description',
  'Audio',
  'Add a link to audio',
  '',
  'Add link to audio',
  'Attribution',
  'Owner or creator',
  '',
  'Owner or creator',
  'Title or Description',
  'Provide the original title or description of the audio.',
  '',
  'Title or description',
  'Start Date',
  'Select a start date or date of single event.',
  '',
  'Select a start date or date of single event',
  'End Date',
  'Select an end date if applicable',
  '',
  'Select an end date if applicable',
  'This case is ongoing',
  '',
  '',
  '',
  'Time Limited or Repeated?',
  'Did this case take place over a single, defined period of days, weeks or months? Or was the entire process repeated over time? Select one.',
  '',
  'Was this time limited or repeated?',
  'A single, defined period of time',
  'Repeated over time',
  'Purpose/Goal',
  'Select and rank up to three purposes, with "1" indicating the most relevant.',
  '',
  'Select & rank up to 3 purposes/goals',
  'Make, influence, or challenge decisions of government and public bodies',
  'Make, influence, or challenge decisions of private organizations (e.g., civil society organizations; corporations)',
  'Deliver goods and services (e.g., co-production of public safety by police and community)',
  'Develop the civic capacities of individuals, communities, and/or civil society organizations (e.g., increase understanding of public issues; strengthen social capital)',
  'Research',
  'Approach',
  'Select and rank up to three approaches, with “1” indicating the most relevant.',
  '',
  'Select & rank up to 3 approaches',
  'Advocacy (e.g. lobbying; petitioning)',
  'Citizenship building (e.g. opportunities for people to learn about their rights & claim them)',
  'Civil society building (e.g. network building across governmental & social boundaries)',
  'Co-governance (e.g. collaboration in decision making with government and public bodies)',
  'Co-production in form of partnership and/or contract with government and/or public bodies (e.g. collaboration with government to provide affordable housing)',
  'Co-production in form of partnership and/or contract with private organisations (e.g. collaboration with business or civil society)',
  'Consultation (e.g. public hearings)',
  'Direct decision making (e.g. referenda)',
  'Independent action (without the participation of government or private bodies)',
  'Informal engagement by intermediaries with nongovernmental authorities (e.g. bargaining & negotiation on behalf of marginalized sectors)',
  'Informal engagement by intermediaries with political authorities (e.g. bargaining & negotiation on behalf of marginalized sectors)',
  'Leadership development (e.g. individual & group capacity for civic engagement)',
  'Evaluation, oversight, & social auditing (e.g. measuring & reporting organizational performance)',
  'Protest (e.g. demonstrations; marches; pickets)',
  'Research (e.g., public opinion surveys; focus groups; participatory action research)',
  'Social mobilization (e.g. community organizing; consciousness raising; political consumerism)',
  'Spectrum of Public Participation',
  'Which type of goal from the IAP2 Spectrum of Public Participation does this case best represent?',
  '',
  'Select one goal',
  'Inform (provide the public with balanced and objective information to assist in understanding the problem, alternatives, opportunities, and/or solutions)',
  'Consult (obtain feedback on analyses, alternatives, and/or decisions)',
  'Involve (work directly with the public throughout the process to ensure that public concerns are understood & considered)',
  'Collaborate (partner with the public in each aspect of the decision including the development of alternatives & the identification of the preferred solution)',
  'Empower (place final decision-making in the hands of the public)',
  'Not applicable or not relevant',
  'Total Number of Participants',
  'Roughly how many people participated?',
  '',
  'How many people participated?',
  'Open to All or Limited to Some?',
  'Was this open to all or limited to a subset of the population?',
  '',
  'Was this open to all or limited to some?',
  'Open to All',
  'Open to All With Special Effort to Recruit Some Groups (e.g. community organizing to recruit low-income earners)',
  'Limited to Only Some Groups or Individuals',
  'Both (i.e. some aspects are open to all and others are limited to some)',
  'Recruitment Method for Limited Subset of Population',
  'If relevant to this case, select the method used to recruit a limited subset of the population.',
  '',
  'Select recruitment method',
  'Captive Sample (e.g. required classroom participation)',
  'Random Sample (i.e. each member of targeted population has equal chance of being either invited or overlooked)',
  'Stratified Random Sample (i.e. participants are selected to reflect the diversity of the population)',
  'Appointment (e.g. city selects members of a consultative council)',
  'Election (e.g. consultative council chosen by election)',
  'Not Applicable',
  'Targeted Demographics',
  'Select up to three of the most heavily recruited groups',
  '',
  'Identify up to 3 recruited groups',
  'Appointed Public Servants (e.g. bureaucrats)',
  'Gay/Lesbian/Bisexual/Transgender (i.e. LGBT)',
  'Elderly',
  'Elected Public Officials',
  'Experts (e.g. scientists)',
  'Indigenous People',
  'Immigrants',
  'Low-Income Earners',
  'Men',
  'People with Disabilities',
  'Racial/Ethnic Groups',
  'Religious Groups',
  'Stakeholder Organizations (e.g. NGOs, business interests)',
  'Students',
  'Women',
  'Youth',
  'General Types of Methods',
  'Select and rank up to three types that best describe the methods used in this case, with "1" indicating the most relevant.',
  'There is huge variety in the range of participatory methods. To help narrow it down, select and rank up to three of the following types of methods used in this case. Specifying what types of methods were used makes it easier for Participedia users to find similar cases.',
  'Select & rank up to 3 types',
  'Collaborative approaches (i.e. two or more stakeholders work together to address a common problem)',
  'Community development, organizing, and mobilization (i.e. empowering communities to drive, implement, and effect change)',
  'Deliberative and dialogic process (i.e. structured processes that involve deliberation and/or dialogue as a central aspect)',
  'Direct democracy (i.e. formal processes by which citizens exert direct authority over decisions)',
  'Evaluation, oversight, and social auditing (i.e.monitoring public bodies and services to hold officials and authorities to account)',
  'Experiential and immersive education (i.e. alternative approaches to teaching and learning)',
  'Informal conversation spaces (i.e. spaces where deliberation and discussion may take place in an informal or unstructured way)',
  'Informal participation (i.e. extra-institutional attempts to secure access to resources, rights and political representation without using formal governmental channels)',
  'Internal management or organization (i.e. systems of internal communication, representation, or decision-making)',
  'Long-term civic bodies (i.e. sustained efforts to provide the public with opportunities for input and decision-making, typically at the local level)',
  'Participant-led meetings (i.e. participants shape the agenda and process)',
  'Participatory arts (i.e. processes that engage audiences as participants in the artistic  production or endeavour)',
  'Planning (i.e. comprehensive approaches to establish goals, policies, and procedures for a social or governmental unit)',
  'Protest (i.e. direct confrontation with public and/or private institutions)',
  'Public budgeting (i.e. designed to help decide how public funds should be spent)',
  'Public meetings (i.e. government-sponsored meetings open to the general public where public officials may also be present)',
  'Research or experimental method (i.e. forms of academic research, or participatory approaches tested as part of a research project)',
  'General Types of Tools/Techniques',
  'Select and rank up to three types that best describe the tools/techniques used in this case, with “1” indicating the most relevant.',
  'There is huge variety in the range of participatory tools/techniques. To help narrow it down, select and rank up to three of the following types that best describe the specific tools/techniques used in this case. Specifying what types of tools/techniques were used is makes it easier for Participedia users to find similar cases.',
  'Select & rank up to 3 types',
  'Manage and/or allocate money or resources (e.g. mobile budgeting applications)',
  'Collect, analyze, and/or solicit feedback (e.g. questionnaire; keypad polling)',
  'Facilitate dialogue, discussion, and/or deliberation (e.g. active listening; managing conflict)',
  'Facilitate decision-making (e.g. ranking; multi-voting)',
  'Legislation, policy, or frameworks (e.g. arrangements that formally embed public participation)',
  'Recruit or select participants (e.g. community outreach; random selection)',
  'Plan, map and/or visualize options and proposals (e.g.GIS mapping)',
  'Propose and/or develop policies, ideas, and recommendations (e.g. brainstorming; nominal group technique)',
  'Inform, educate and/or raise awareness (e.g. discussion guide; Q&A with experts)',
  'Specific Methods, Tools & Techniques',
  'What specific methods, tools and techniques were used in this case? Type to select from entries already in the Participedia database.',
  '',
  'Type to search & generate possible database matches',
  'Legality',
  'Is the overall method used in this case considered legal by judicial authorities?',
  '',
  'Was this considered legal?',
  'Yes',
  'No',
  'Don’t know',
  'Facilitators',
  'Did facilitators help guide part or all of this case?',
  '',
  'Was this considered legal?',
  'Yes',
  'No',
  'Not Applicable',
  'Facilitator Training',
  'What level of training did facilitators have?',
  '',
  'Select the type of facilitators',
  'Professional Facilitators',
  'Trained, Nonprofessional Facilitators',
  'Untrained, Nonprofessional Facilitators',
  'Face-to-Face, Online, or Both',
  'Did participants interact face-to-face, online, or both?',
  '',
  'Was interaction face-to-face or online?',
  'Face-to-Face',
  'Online',
  'Both',
  'Types of Interaction Among Participants',
  'Select and rank up to three types of interactions in order of relevance, with with “1” indicating the most often used form of interaction.',
  '',
  'Select & rank up to 3 types of interaction',
  'Acting, Drama, or Roleplay',
  'Ask & Answer Questions',
  'Discussion, Dialogue, or Deliberation',
  'Express Opinions/Preferences Only',
  'Formal Testimony',
  'Informal Social Activities',
  'Listen/Watch as Spectator',
  'Negotiation & Bargaining',
  'Storytelling',
  'Teaching/Instructing',
  'No Interaction Among Participants',
  'Information & Learning Resources',
  'What types of background information were provided for participants?',
  '',
  'Identify information (if any) provided',
  'Expert Presentations',
  'Participant Presentations',
  'Site Visits',
  'Teach-ins',
  'Video Presentations (online or in-person)',
  'Written Briefing Materials (online or as handouts)',
  'No Information Was Provided to Participants',
  'Not Relevant to this Type of Initiative',
  'Decision Methods',
  'How did participants in this case make group decisions?',
  '',
  'How were group decisions made?',
  'Opinion Survey (i.e. taken before and/or after participants convened)',
  'Idea Generation (i.e. potential solutions were generated, but no priorities were decided)',
  'General Agreement/Consensus (i.e. broad acceptance of decisions; unanimous agreement desired but not necessary)',
  'Voting (i.e. any type of formal vote; please provide more detail in next field)',
  'Not Applicable (e.g. votes are not typically taken at protest demonstrations)',
  'Don’t Know',
  'If Voting',
  'What voting methods were used by participants?',
  '',
  'What voting methods were used?',
  'Preferential Voting (i.e. ranked preferences)',
  'Plurality (i.e. highest percentage wins, even if the proposal receives fewer than 50.1% votes)',
  'Majoritarian Voting (i.e. 50% +1)',
  'Super-Majoritarian (i.e. threshold more than 50% +1)',
  'Unanimous Decision (i.e. full agreement by all participants)',
  'Don’t Know',
  'Communication of Insights & Outcomes',
  'Select up to three ways that insights and outcomes from this case were communicated to the intended audiences.',
  '',
  'How were insights & outcomes communicated?',
  'Artistic Expression (e.g. political rap, street theater)',
  'Traditional Media (i.e. television, radio, newspapers)',
  'New Media (e.g. social media, blogging, texting)',
  'Independent Media (i.e. free of corporate or government influence)',
  'Public Report',
  'Minority Report (i.e. a dissenting opinion)',
  'Petitions',
  'Protests/Public Demonstrations',
  'Public Hearings/Meetings',
  'Word of Mouth',
  'Not Applicable',
  'Primary Organizer/Manager',
  'Who was primarily responsible for organizing / managing the initiative? Type to select name of any organization that already exists on Participedia. For new organizations, first publish this case to save your work then publish a new organization. To add your new organization, return to edit this case.',
  'Provide information about additional organizers and sponsors of the initiative in the "Originating Entities and Funding" section of the case narrative.',
  'Type to search & generate possible database matches',
  'Type of Organizer/Manager',
  'Select up to three types of organizers or managers.',
  '',
  'Select up to 3 types of organizers or managers',
  'Academic Institution',
  'Activist Network',
  'Community Based Organization',
  'Faith-Based Organization',
  'For-Profit Business',
  'Government-Owned Corporation',
  'Individual',
  'International Organization',
  'Local Government (e.g. Village, Town, City)',
  'National Government',
  'Non-Governmental Organization (Non-profit)',
  'Philanthropic Organization (i.e. dedicated to making monetary grants or gifts)',
  'Regional Government (e.g. State, Provincial, Territorial)',
  'Social Movement',
  'Labor/Trade Union',
  'Not Applicable',
  'Funder',
  'Who funded this case of public participation? Provide names of the organizations, government agencies, or individuals who paid for this initiative.',
  'Provide additional information about funders of the initiative in the "Originating Entities and Funding" section of the case narrative.',
  'Who funded this case?',
  'Types of Funder',
  '',
  '',
  '',
  'Academic Institution',
  'Activist Network',
  'Community Based Organization',
  'Faith-Based Organization',
  'For-Profit Business',
  'Government-Owned Corporation',
  'Individual',
  'International Organization',
  'Local Government (e.g. Village, Town, City)',
  'National Government',
  'Non-Governmental Organization (Non-profit)',
  'Philanthropic Organization (i.e. dedicated to making monetary grants or gifts)',
  'Regional Government (e.g. State, Provincial, Territorial)',
  'Social Movement',
  'Labor/Trade Union',
  'Not Applicable',
  'Staff',
  'Were any paid staff or consultants involved in this case?',
  '',
  'Were paid staff or consultants involved?',
  'Volunteers',
  'Did unpaid volunteers help implement this case?',
  '',
  'Were unpaid volunteers involved?',
  'Evidence of Impact',
  'Did this initiative contribute to social and/or political change?',
  '',
  'Did this work contribute to social or political change?',
  'Types of Change',
  'Select and rank up to five types of change to which this case contributed, in order of relevance, with "1" being the most relevant type of change.',
  'Provide additional detail in the "Influence, Outcomes, and Effects" section of the case narrative.',
  'Select & rank up to 5 types of change to which this case contributed',
  'Changes in people’s knowledge, attitudes, and behavior',
  'Changes in civic capacities (e.g. improved community problem solving)',
  'Changes in public policy (e.g. new laws or regulations)',
  'Changes in how institutions operate (e.g. improved decision making)',
  'Conflict transformation',
  'Implementers of Change',
  'Select up to three types of actors who played roles in implementing ideas that emerged from this initiative.',
  '',
  'Select & rank up to 3 types of implementers of change',
  'Lay Public (i.e. people with no professional stake in the issues)',
  'Stakeholder Organizations (e.g. community groups, NGOs, business interests)',
  'Elected Public Officials',
  'Appointed Public Servants (e.g. bureaucrats)',
  'Experts (e.g. scientists, engineers, criminologists, doctors, lawyers)',
  'Corporations',
  'Don’t Know',
  'Formal Evaluation',
  'Was a formal evaluation of this initiative conducted?',
  '',
  'Was there a formal evaluation of this case?',
  'Evaluation Report Document',
  'Upload evaluation report from your device.',
  '',
  'Upload relevant documents',
  'Evaluation Report Link',
  'Provide a link to the evaluation report here.',
  '',
  'Add a link'
);
