CREATE TABLE scope_case_value_localized (
  language TEXT NOT NULL,
  organization_long TEXT DEFAULT 'Localized organization long form',
  organization_short TEXT DEFAULT 'Localized organization short form',
  neighbourhood_long TEXT DEFAULT 'Localized neighbourhood long form',
  neighbourhood_short TEXT DEFAULT 'Localized neighbourhood short form',
  city_long TEXT DEFAULT 'Localized city long form',
  city_short TEXT DEFAULT 'Localized city short form',
  metropolitan_long TEXT DEFAULT 'Localized metropolitan long form',
  metropolitan_short TEXT DEFAULT 'Localized metropolitan short form',
  regional_long TEXT DEFAULT 'Localized regional long form',
  regional_short TEXT DEFAULT 'Localized regional short form',
  national_long TEXT DEFAULT 'Localized national long form',
  national_short TEXT DEFAULT 'Localized national short form',
  multinational_long TEXT DEFAULT 'Localized multinational long form',
  multinational_short TEXT DEFAULT 'Localized multinational short form',
  no_limit_long TEXT DEFAULT 'Localized no_limit long form',
  no_limit_short TEXT DEFAULT 'Localized no_limit short form'
);

CREATE TABLE time_limited_case_value_localized (
  language TEXT NOT NULL,
  single_long TEXT DEFAULT 'Localized single long form',
  single_short TEXT DEFAULT 'Localized single short form',
  repeated_long TEXT DEFAULT 'Localized repeated long form',
  repeated_short TEXT DEFAULT 'Localized repeated short form'
);

CREATE TABLE purpose_case_value_localized (
  language TEXT NOT NULL,
  public_long TEXT DEFAULT 'Localized public long form',
  public_short TEXT DEFAULT 'Localized public short form',
  private_long TEXT DEFAULT 'Localized private long form',
  private_short TEXT DEFAULT 'Localized private short form',
  goods_long TEXT DEFAULT 'Localized goods long form',
  goods_short TEXT DEFAULT 'Localized goods short form',
  civic_long TEXT DEFAULT 'Localized civic long form',
  civic_short TEXT DEFAULT 'Localized civic short form',
  research_long TEXT DEFAULT 'Localized research long form',
  research_short TEXT DEFAULT 'Localized research short form'
);

CREATE TABLE approach_case_value_localized (
  language TEXT NOT NULL,
  advocacy_long TEXT DEFAULT 'Localized advocacy long form',
  advocacy_short TEXT DEFAULT 'Localized advocacy short form',
  citizenship_long TEXT DEFAULT 'Localized citizenship long form',
  citizenship_short TEXT DEFAULT 'Localized citizenship short form',
  civil_long TEXT DEFAULT 'Localized civil long form',
  civil_short TEXT DEFAULT 'Localized civil short form',
  cogovernance_long TEXT DEFAULT 'Localized cogovernance long form',
  cogovernance_short TEXT DEFAULT 'Localized cogovernance short form',
  public_partner_long TEXT DEFAULT 'Localized public_partner long form',
  public_partner_short TEXT DEFAULT 'Localized public_partner short form',
  private_partner_long TEXT DEFAULT 'Localized private_partner long form',
  private_partner_short TEXT DEFAULT 'Localized private_partner short form',
  consultation_long TEXT DEFAULT 'Localized consultation long form',
  consultation_short TEXT DEFAULT 'Localized consultation short form',
  decision_long TEXT DEFAULT 'Localized decision long form',
  decision_short TEXT DEFAULT 'Localized decision short form',
  independent_long TEXT DEFAULT 'Localized independent long form',
  independent_short TEXT DEFAULT 'Localized independent short form',
  nongovernmental_long TEXT DEFAULT 'Localized nongovernmental long form',
  nongovernmental_short TEXT DEFAULT 'Localized nongovernmental short form',
  political_long TEXT DEFAULT 'Localized political long form',
  political_short TEXT DEFAULT 'Localized political short form',
  leadership_long TEXT DEFAULT 'Localized leadership long form',
  leadership_short TEXT DEFAULT 'Localized leadership short form',
  auditing_long TEXT DEFAULT 'Localized auditing long form',
  auditing_short TEXT DEFAULT 'Localized auditing short form',
  protest_long TEXT DEFAULT 'Localized protest long form',
  protest_short TEXT DEFAULT 'Localized protest short form',
  research_long TEXT DEFAULT 'Localized research long form',
  research_short TEXT DEFAULT 'Localized research short form',
  mobilization_long TEXT DEFAULT 'Localized mobilization long form',
  mobilization_short TEXT DEFAULT 'Localized mobilization short form'
);

CREATE TABLE public_spectrum_case_value_localized (
  language TEXT NOT NULL,
  inform_long TEXT DEFAULT 'Localized inform long form',
  inform_short TEXT DEFAULT 'Localized inform short form',
  consult_long TEXT DEFAULT 'Localized consult long form',
  consult_short TEXT DEFAULT 'Localized consult short form',
  involve_long TEXT DEFAULT 'Localized involve long form',
  involve_short TEXT DEFAULT 'Localized involve short form',
  collaborate_long TEXT DEFAULT 'Localized collaborate long form',
  collaborate_short TEXT DEFAULT 'Localized collaborate short form',
  empower_long TEXT DEFAULT 'Localized empower long form',
  empower_short TEXT DEFAULT 'Localized empower short form',
  na_long TEXT DEFAULT 'Localized na long form',
  na_short TEXT DEFAULT 'Localized na short form'
);

CREATE TABLE open_limited_case_value_localized (
  language TEXT NOT NULL,
  all_long TEXT DEFAULT 'Localized all long form',
  all_short TEXT DEFAULT 'Localized all short form',
  special_long TEXT DEFAULT 'Localized special long form',
  special_short TEXT DEFAULT 'Localized special short form',
  limited_long TEXT DEFAULT 'Localized limited long form',
  limited_short TEXT DEFAULT 'Localized limited short form',
  both_long TEXT DEFAULT 'Localized both long form',
  both_short TEXT DEFAULT 'Localized both short form'
);

CREATE TABLE recruitment_method_case_value_localized (
  language TEXT NOT NULL,
  captive_long TEXT DEFAULT 'Localized captive long form',
  captive_short TEXT DEFAULT 'Localized captive short form',
  random_long TEXT DEFAULT 'Localized random long form',
  random_short TEXT DEFAULT 'Localized random short form',
  stratified_long TEXT DEFAULT 'Localized stratified long form',
  stratified_short TEXT DEFAULT 'Localized stratified short form',
  appointment_long TEXT DEFAULT 'Localized appointment long form',
  appointment_short TEXT DEFAULT 'Localized appointment short form',
  election_long TEXT DEFAULT 'Localized election long form',
  election_short TEXT DEFAULT 'Localized election short form',
  na_long TEXT DEFAULT 'Localized na long form',
  na_short TEXT DEFAULT 'Localized na short form'
);

CREATE TABLE targeted_participants_case_value_localized (
  language TEXT NOT NULL,
  appointed_long TEXT DEFAULT 'Localized appointed long form',
  appointed_short TEXT DEFAULT 'Localized appointed short form',
  lgbt_long TEXT DEFAULT 'Localized lgbt long form',
  lgbt_short TEXT DEFAULT 'Localized lgbt short form',
  elderly_long TEXT DEFAULT 'Localized elderly long form',
  elderly_short TEXT DEFAULT 'Localized elderly short form',
  elected_long TEXT DEFAULT 'Localized elected long form',
  elected_short TEXT DEFAULT 'Localized elected short form',
  experts_long TEXT DEFAULT 'Localized experts long form',
  experts_short TEXT DEFAULT 'Localized experts short form',
  indigenous_long TEXT DEFAULT 'Localized indigenous long form',
  indigenous_short TEXT DEFAULT 'Localized indigenous short form',
  immigrants_long TEXT DEFAULT 'Localized immigrants long form',
  immigrants_short TEXT DEFAULT 'Localized immigrants short form',
  low_income_long TEXT DEFAULT 'Localized low_income long form',
  low_income_short TEXT DEFAULT 'Localized low_income short form',
  men_long TEXT DEFAULT 'Localized men long form',
  men_short TEXT DEFAULT 'Localized men short form',
  disabilities_long TEXT DEFAULT 'Localized disabilities long form',
  disabilities_short TEXT DEFAULT 'Localized disabilities short form',
  ethnic_long TEXT DEFAULT 'Localized ethnic long form',
  ethnic_short TEXT DEFAULT 'Localized ethnic short form',
  religious_long TEXT DEFAULT 'Localized religious long form',
  religious_short TEXT DEFAULT 'Localized religious short form',
  stakeholders_long TEXT DEFAULT 'Localized stakeholders long form',
  stakeholders_short TEXT DEFAULT 'Localized stakeholders short form',
  students_long TEXT DEFAULT 'Localized students long form',
  students_short TEXT DEFAULT 'Localized students short form',
  women_long TEXT DEFAULT 'Localized women long form',
  women_short TEXT DEFAULT 'Localized women short form',
  youth_long TEXT DEFAULT 'Localized youth long form',
  youth_short TEXT DEFAULT 'Localized youth short form'
);

CREATE TABLE method_types_case_value_localized (
  language TEXT NOT NULL,
  _long TEXT DEFAULT 'Localized  long form',
  _short TEXT DEFAULT 'Localized  short form',
  community_long TEXT DEFAULT 'Localized community long form',
  community_short TEXT DEFAULT 'Localized community short form',
  deliberative_long TEXT DEFAULT 'Localized deliberative long form',
  deliberative_short TEXT DEFAULT 'Localized deliberative short form',
  democracy_long TEXT DEFAULT 'Localized democracy long form',
  democracy_short TEXT DEFAULT 'Localized democracy short form',
  auditing_long TEXT DEFAULT 'Localized auditing long form',
  auditing_short TEXT DEFAULT 'Localized auditing short form',
  education_long TEXT DEFAULT 'Localized education long form',
  education_short TEXT DEFAULT 'Localized education short form',
  conversation_long TEXT DEFAULT 'Localized conversation long form',
  conversation_short TEXT DEFAULT 'Localized conversation short form',
  participation_long TEXT DEFAULT 'Localized participation long form',
  participation_short TEXT DEFAULT 'Localized participation short form',
  management_long TEXT DEFAULT 'Localized management long form',
  management_short TEXT DEFAULT 'Localized management short form',
  civic_long TEXT DEFAULT 'Localized civic long form',
  civic_short TEXT DEFAULT 'Localized civic short form',
  participant_meetings_long TEXT DEFAULT 'Localized participant_meetings long form',
  participant_meetings_short TEXT DEFAULT 'Localized participant_meetings short form',
  arts_long TEXT DEFAULT 'Localized arts long form',
  arts_short TEXT DEFAULT 'Localized arts short form',
  planning_long TEXT DEFAULT 'Localized planning long form',
  planning_short TEXT DEFAULT 'Localized planning short form',
  protest_long TEXT DEFAULT 'Localized protest long form',
  protest_short TEXT DEFAULT 'Localized protest short form',
  budgeting_long TEXT DEFAULT 'Localized budgeting long form',
  budgeting_short TEXT DEFAULT 'Localized budgeting short form',
  public_meetings_long TEXT DEFAULT 'Localized public_meetings long form',
  public_meetings_short TEXT DEFAULT 'Localized public_meetings short form',
  research_long TEXT DEFAULT 'Localized research long form',
  research_short TEXT DEFAULT 'Localized research short form'
);

CREATE TABLE tool_types_case_value_localized (
  language TEXT NOT NULL,
  money_long TEXT DEFAULT 'Localized money long form',
  money_short TEXT DEFAULT 'Localized money short form',
  feedback_long TEXT DEFAULT 'Localized feedback long form',
  feedback_short TEXT DEFAULT 'Localized feedback short form',
  dialogue_long TEXT DEFAULT 'Localized dialogue long form',
  dialogue_short TEXT DEFAULT 'Localized dialogue short form',
  decisions_long TEXT DEFAULT 'Localized decisions long form',
  decisions_short TEXT DEFAULT 'Localized decisions short form',
  legislation_long TEXT DEFAULT 'Localized legislation long form',
  legislation_short TEXT DEFAULT 'Localized legislation short form',
  recruit_long TEXT DEFAULT 'Localized recruit long form',
  recruit_short TEXT DEFAULT 'Localized recruit short form',
  map_long TEXT DEFAULT 'Localized map long form',
  map_short TEXT DEFAULT 'Localized map short form',
  policies_long TEXT DEFAULT 'Localized policies long form',
  policies_short TEXT DEFAULT 'Localized policies short form',
  educate_long TEXT DEFAULT 'Localized educate long form',
  educate_short TEXT DEFAULT 'Localized educate short form'
);

CREATE TABLE legality_case_value_localized (
  language TEXT NOT NULL,
  yes_long TEXT DEFAULT 'Localized yes long form',
  yes_short TEXT DEFAULT 'Localized yes short form',
  no_long TEXT DEFAULT 'Localized no long form',
  no_short TEXT DEFAULT 'Localized no short form',
  idk_long TEXT DEFAULT 'Localized idk long form',
  idk_short TEXT DEFAULT 'Localized idk short form'
);

CREATE TABLE facilitators_case_value_localized (
  language TEXT NOT NULL,
  yes_long TEXT DEFAULT 'Localized yes long form',
  yes_short TEXT DEFAULT 'Localized yes short form',
  no_long TEXT DEFAULT 'Localized no long form',
  no_short TEXT DEFAULT 'Localized no short form',
  na_long TEXT DEFAULT 'Localized na long form',
  na_short TEXT DEFAULT 'Localized na short form'
);

CREATE TABLE facilitator_training_case_value_localized (
  language TEXT NOT NULL,
  professional_long TEXT DEFAULT 'Localized professional long form',
  professional_short TEXT DEFAULT 'Localized professional short form',
  trained_long TEXT DEFAULT 'Localized trained long form',
  trained_short TEXT DEFAULT 'Localized trained short form',
  untrained_long TEXT DEFAULT 'Localized untrained long form',
  untrained_short TEXT DEFAULT 'Localized untrained short form'
);

CREATE TABLE facetoface_case_value_localized (
  language TEXT NOT NULL,
  facetoface_long TEXT DEFAULT 'Localized facetoface long form',
  facetoface_short TEXT DEFAULT 'Localized facetoface short form',
  online_long TEXT DEFAULT 'Localized online long form',
  online_short TEXT DEFAULT 'Localized online short form',
  both_long TEXT DEFAULT 'Localized both long form',
  both_short TEXT DEFAULT 'Localized both short form'
);

CREATE TABLE participants_interaction_case_value_localized (
  language TEXT NOT NULL,
  drama_long TEXT DEFAULT 'Localized drama long form',
  drama_short TEXT DEFAULT 'Localized drama short form',
  questions_long TEXT DEFAULT 'Localized questions long form',
  questions_short TEXT DEFAULT 'Localized questions short form',
  dialogue_long TEXT DEFAULT 'Localized dialogue long form',
  dialogue_short TEXT DEFAULT 'Localized dialogue short form',
  opinions_long TEXT DEFAULT 'Localized opinions long form',
  opinions_short TEXT DEFAULT 'Localized opinions short form',
  testimony_long TEXT DEFAULT 'Localized testimony long form',
  testimony_short TEXT DEFAULT 'Localized testimony short form',
  social_long TEXT DEFAULT 'Localized social long form',
  social_short TEXT DEFAULT 'Localized social short form',
  spectator_long TEXT DEFAULT 'Localized spectator long form',
  spectator_short TEXT DEFAULT 'Localized spectator short form',
  bargaining_long TEXT DEFAULT 'Localized bargaining long form',
  bargaining_short TEXT DEFAULT 'Localized bargaining short form',
  storytelling_long TEXT DEFAULT 'Localized storytelling long form',
  storytelling_short TEXT DEFAULT 'Localized storytelling short form',
  teaching_long TEXT DEFAULT 'Localized teaching long form',
  teaching_short TEXT DEFAULT 'Localized teaching short form',
  none_long TEXT DEFAULT 'Localized none long form',
  none_short TEXT DEFAULT 'Localized none short form'
);

CREATE TABLE learning_resources_case_value_localized (
  language TEXT NOT NULL,
  expert_long TEXT DEFAULT 'Localized expert long form',
  expert_short TEXT DEFAULT 'Localized expert short form',
  participant_long TEXT DEFAULT 'Localized participant long form',
  participant_short TEXT DEFAULT 'Localized participant short form',
  visits_long TEXT DEFAULT 'Localized visits long form',
  visits_short TEXT DEFAULT 'Localized visits short form',
  teach_long TEXT DEFAULT 'Localized teach long form',
  teach_short TEXT DEFAULT 'Localized teach short form',
  video_long TEXT DEFAULT 'Localized video long form',
  video_short TEXT DEFAULT 'Localized video short form',
  written_long TEXT DEFAULT 'Localized written long form',
  written_short TEXT DEFAULT 'Localized written short form',
  none_long TEXT DEFAULT 'Localized none long form',
  none_short TEXT DEFAULT 'Localized none short form',
  na_long TEXT DEFAULT 'Localized na long form',
  na_short TEXT DEFAULT 'Localized na short form'
);

CREATE TABLE decision_methods_case_value_localized (
  language TEXT NOT NULL,
  opinion_long TEXT DEFAULT 'Localized opinion long form',
  opinion_short TEXT DEFAULT 'Localized opinion short form',
  ideas_long TEXT DEFAULT 'Localized ideas long form',
  ideas_short TEXT DEFAULT 'Localized ideas short form',
  agreement_long TEXT DEFAULT 'Localized agreement long form',
  agreement_short TEXT DEFAULT 'Localized agreement short form',
  voting_long TEXT DEFAULT 'Localized voting long form',
  voting_short TEXT DEFAULT 'Localized voting short form',
  na_long TEXT DEFAULT 'Localized na long form',
  na_short TEXT DEFAULT 'Localized na short form',
  idk_long TEXT DEFAULT 'Localized idk long form',
  idk_short TEXT DEFAULT 'Localized idk short form'
);

CREATE TABLE if_voting_case_value_localized (
  language TEXT NOT NULL,
  preferential_long TEXT DEFAULT 'Localized preferential long form',
  preferential_short TEXT DEFAULT 'Localized preferential short form',
  plurality_long TEXT DEFAULT 'Localized plurality long form',
  plurality_short TEXT DEFAULT 'Localized plurality short form',
  majoritarian_long TEXT DEFAULT 'Localized majoritarian long form',
  majoritarian_short TEXT DEFAULT 'Localized majoritarian short form',
  super_long TEXT DEFAULT 'Localized super long form',
  super_short TEXT DEFAULT 'Localized super short form',
  unanimous_long TEXT DEFAULT 'Localized unanimous long form',
  unanimous_short TEXT DEFAULT 'Localized unanimous short form',
  dk_long TEXT DEFAULT 'Localized dk long form',
  dk_short TEXT DEFAULT 'Localized dk short form'
);

CREATE TABLE insights_outcomes_case_value_localized (
  language TEXT NOT NULL,
  artistic_long TEXT DEFAULT 'Localized artistic long form',
  artistic_short TEXT DEFAULT 'Localized artistic short form',
  media_long TEXT DEFAULT 'Localized media long form',
  media_short TEXT DEFAULT 'Localized media short form',
  social_long TEXT DEFAULT 'Localized social long form',
  social_short TEXT DEFAULT 'Localized social short form',
  independent_long TEXT DEFAULT 'Localized independent long form',
  independent_short TEXT DEFAULT 'Localized independent short form',
  report_long TEXT DEFAULT 'Localized report long form',
  report_short TEXT DEFAULT 'Localized report short form',
  minority_long TEXT DEFAULT 'Localized minority long form',
  minority_short TEXT DEFAULT 'Localized minority short form',
  petitions_long TEXT DEFAULT 'Localized petitions long form',
  petitions_short TEXT DEFAULT 'Localized petitions short form',
  protests_long TEXT DEFAULT 'Localized protests long form',
  protests_short TEXT DEFAULT 'Localized protests short form',
  hearings_long TEXT DEFAULT 'Localized hearings long form',
  hearings_short TEXT DEFAULT 'Localized hearings short form',
  wordofmouth_long TEXT DEFAULT 'Localized wordofmouth long form',
  wordofmouth_short TEXT DEFAULT 'Localized wordofmouth short form',
  na_long TEXT DEFAULT 'Localized na long form',
  na_short TEXT DEFAULT 'Localized na short form'
);

CREATE TABLE organizer_type_case_value_localized (
  language TEXT NOT NULL,
  academic_long TEXT DEFAULT 'Localized academic long form',
  academic_short TEXT DEFAULT 'Localized academic short form',
  activist_long TEXT DEFAULT 'Localized activist long form',
  activist_short TEXT DEFAULT 'Localized activist short form',
  community_long TEXT DEFAULT 'Localized community long form',
  community_short TEXT DEFAULT 'Localized community short form',
  faith_long TEXT DEFAULT 'Localized faith long form',
  faith_short TEXT DEFAULT 'Localized faith short form',
  business_long TEXT DEFAULT 'Localized business long form',
  business_short TEXT DEFAULT 'Localized business short form',
  government_corp_long TEXT DEFAULT 'Localized government_corp long form',
  government_corp_short TEXT DEFAULT 'Localized government_corp short form',
  individual_long TEXT DEFAULT 'Localized individual long form',
  individual_short TEXT DEFAULT 'Localized individual short form',
  international_long TEXT DEFAULT 'Localized international long form',
  international_short TEXT DEFAULT 'Localized international short form',
  local_government_long TEXT DEFAULT 'Localized local_government long form',
  local_government_short TEXT DEFAULT 'Localized local_government short form',
  national_government_long TEXT DEFAULT 'Localized national_government long form',
  national_government_short TEXT DEFAULT 'Localized national_government short form',
  ngo_long TEXT DEFAULT 'Localized ngo long form',
  ngo_short TEXT DEFAULT 'Localized ngo short form',
  philanthropic_long TEXT DEFAULT 'Localized philanthropic long form',
  philanthropic_short TEXT DEFAULT 'Localized philanthropic short form',
  regional_government_long TEXT DEFAULT 'Localized regional_government long form',
  regional_government_short TEXT DEFAULT 'Localized regional_government short form',
  social_long TEXT DEFAULT 'Localized social long form',
  social_short TEXT DEFAULT 'Localized social short form',
  labour_long TEXT DEFAULT 'Localized labour long form',
  labour_short TEXT DEFAULT 'Localized labour short form',
  na_long TEXT DEFAULT 'Localized na long form',
  na_short TEXT DEFAULT 'Localized na short form'
);

CREATE TABLE funder_types_case_value_localized (
  language TEXT NOT NULL,
  academic_long TEXT DEFAULT 'Localized academic long form',
  academic_short TEXT DEFAULT 'Localized academic short form',
  activist_long TEXT DEFAULT 'Localized activist long form',
  activist_short TEXT DEFAULT 'Localized activist short form',
  community_long TEXT DEFAULT 'Localized community long form',
  community_short TEXT DEFAULT 'Localized community short form',
  faith_long TEXT DEFAULT 'Localized faith long form',
  faith_short TEXT DEFAULT 'Localized faith short form',
  business_long TEXT DEFAULT 'Localized business long form',
  business_short TEXT DEFAULT 'Localized business short form',
  government_corp_long TEXT DEFAULT 'Localized government_corp long form',
  government_corp_short TEXT DEFAULT 'Localized government_corp short form',
  individual_long TEXT DEFAULT 'Localized individual long form',
  individual_short TEXT DEFAULT 'Localized individual short form',
  international_long TEXT DEFAULT 'Localized international long form',
  international_short TEXT DEFAULT 'Localized international short form',
  local_government_long TEXT DEFAULT 'Localized local_government long form',
  local_government_short TEXT DEFAULT 'Localized local_government short form',
  national_government_long TEXT DEFAULT 'Localized national_government long form',
  national_government_short TEXT DEFAULT 'Localized national_government short form',
  ngo_long TEXT DEFAULT 'Localized ngo long form',
  ngo_short TEXT DEFAULT 'Localized ngo short form',
  philanthropic_long TEXT DEFAULT 'Localized philanthropic long form',
  philanthropic_short TEXT DEFAULT 'Localized philanthropic short form',
  regional_government_long TEXT DEFAULT 'Localized regional_government long form',
  regional_government_short TEXT DEFAULT 'Localized regional_government short form',
  social_long TEXT DEFAULT 'Localized social long form',
  social_short TEXT DEFAULT 'Localized social short form',
  labour_long TEXT DEFAULT 'Localized labour long form',
  labour_short TEXT DEFAULT 'Localized labour short form',
  na_long TEXT DEFAULT 'Localized na long form',
  na_short TEXT DEFAULT 'Localized na short form'
);

CREATE TABLE change_types_case_value_localized (
  language TEXT NOT NULL,
  behaviour_long TEXT DEFAULT 'Localized behaviour long form',
  behaviour_short TEXT DEFAULT 'Localized behaviour short form',
  capacities_long TEXT DEFAULT 'Localized capacities long form',
  capacities_short TEXT DEFAULT 'Localized capacities short form',
  policy_long TEXT DEFAULT 'Localized policy long form',
  policy_short TEXT DEFAULT 'Localized policy short form',
  operations_long TEXT DEFAULT 'Localized operations long form',
  operations_short TEXT DEFAULT 'Localized operations short form',
  transformation_long TEXT DEFAULT 'Localized transformation long form',
  transformation_short TEXT DEFAULT 'Localized transformation short form'
);

CREATE TABLE implementers_of_change_case_value_localized (
  language TEXT NOT NULL,
  public_long TEXT DEFAULT 'Localized public long form',
  public_short TEXT DEFAULT 'Localized public short form',
  stakeholders_long TEXT DEFAULT 'Localized stakeholders long form',
  stakeholders_short TEXT DEFAULT 'Localized stakeholders short form',
  elected_long TEXT DEFAULT 'Localized elected long form',
  elected_short TEXT DEFAULT 'Localized elected short form',
  appointed_long TEXT DEFAULT 'Localized appointed long form',
  appointed_short TEXT DEFAULT 'Localized appointed short form',
  experts_long TEXT DEFAULT 'Localized experts long form',
  experts_short TEXT DEFAULT 'Localized experts short form',
  corporations_long TEXT DEFAULT 'Localized corporations long form',
  corporations_short TEXT DEFAULT 'Localized corporations short form',
  idk_long TEXT DEFAULT 'Localized idk long form',
  idk_short TEXT DEFAULT 'Localized idk short form'
);

INSERT INTO scope_case_value_localized VALUES (
  'en',
  'Organization (e.g. a local business or cooperative using participatory methods to manage and govern itself)',
  'Organization',
  'Neighbourhood',
  'Neighbourhood',
  'City/Town',
  'City/Town',
  'Metropolitan Area',
  'Metropolitan Area',
  'Regional (e.g. State, Province, Autonomous Region)',
  'Regional',
  'National',
  'National',
  'Multinational',
  'Multinational',
  'No Geographical Limits (e.g. online environment where anyone from any place can take part)',
  'No Geographical Limits'
);

INSERT INTO time_limited_case_value_localized VALUES (
  'en',
  'A single, defined period of time',
  'A single, defined period of time',
  'Repeated over time',
  'Repeated over time'
);

INSERT INTO purpose_case_value_localized VALUES (
  'en',
  'Make, influence, or challenge decisions of government and public bodies',
  'Make, influence, or challenge decisions of government and public bodies',
  'Make, influence, or challenge decisions of private organizations (e.g., civil society organizations; corporations)',
  'Make, influence, or challenge decisions of private organizations',
  'Deliver goods and services (e.g., co-production of public safety by police and community)',
  'Deliver goods and services',
  'Develop the civic capacities of individuals, communities, and/or civil society organizations (e.g., increase understanding of public issues; strengthen social capital)',
  'Develop the civic capacities of individuals, communities, and/or civil society organizations',
  'Research',
  'Research'
);

INSERT INTO approach_case_value_localized VALUES (
  'en',
  'Advocacy (e.g. lobbying; petitioning)',
  'Advocacy',
  'Citizenship building (e.g. opportunities for people to learn about their rights & claim them)',
  'Citizenship building',
  'Civil society building (e.g. network building across governmental & social boundaries)',
  'Civil society building',
  'Co-governance (e.g. collaboration in decision making with government and public bodies)',
  'Co-governance',
  'Co-production in form of partnership and/or contract with government and/or public bodies (e.g. collaboration with government to provide affordable housing)',
  'Co-production in form of partnership and/or contract with government and/or public bodies',
  'Co-production in form of partnership and/or contract with private organisations (e.g. collaboration with business or civil society)',
  'Co-production in form of partnership and/or contract with private organisations',
  'Consultation (e.g. public hearings)',
  'Consultation',
  'Direct decision making (e.g. referenda)',
  'Direct decision making',
  'Independent action (without the participation of government or private bodies)',
  'Independent action',
  'Informal engagement by intermediaries with nongovernmental authorities (e.g. bargaining & negotiation on behalf of marginalized sectors)',
  'Informal engagement by intermediaries with nongovernmental authorities',
  'Informal engagement by intermediaries with political authorities (e.g. bargaining & negotiation on behalf of marginalized sectors)',
  'Informal engagement by intermediaries with political authorities',
  'Leadership development (e.g. individual & group capacity for civic engagement)',
  'Leadership development',
  'Evaluation, oversight, & social auditing (e.g. measuring & reporting organizational performance)',
  'Evaluation, oversight, & social auditing',
  'Protest (e.g. demonstrations; marches; pickets)',
  'Protest',
  'Research (e.g., public opinion surveys; focus groups; participatory action research)',
  'Research',
  'Social mobilization (e.g. community organizing; consciousness raising; political consumerism)',
  'Social mobilization'
);

INSERT INTO public_spectrum_case_value_localized VALUES (
  'en',
  'Inform (provide the public with balanced and objective information to assist in understanding the problem, alternatives, opportunities, and/or solutions)',
  'Inform',
  'Consult (obtain feedback on analyses, alternatives, and/or decisions)',
  'Consult',
  'Involve (work directly with the public throughout the process to ensure that public concerns are understood & considered)',
  'Involve',
  'Collaborate (partner with the public in each aspect of the decision including the development of alternatives & the identification of the preferred solution)',
  'Collaborate',
  'Empower (place final decision-making in the hands of the public)',
  'Empower',
  'Not applicable or not relevant',
  'Not applicable or not relevant'
);

INSERT INTO open_limited_case_value_localized VALUES (
  'en',
  'Open to All',
  'Open to All',
  'Open to All With Special Effort to Recruit Some Groups (e.g. community organizing to recruit low-income earners)',
  'Open to All With Special Effort to Recruit Some Groups',
  'Limited to Only Some Groups or Individuals',
  'Limited to Only Some Groups or Individuals',
  'Both (i.e. some aspects are open to all and others are limited to some)',
  'Both'
);

INSERT INTO recruitment_method_case_value_localized VALUES (
  'en',
  'Captive Sample (e.g. required classroom participation)',
  'Captive Sample',
  'Random Sample (i.e. each member of targeted population has equal chance of being either invited or overlooked)',
  'Random Sample',
  'Stratified Random Sample (i.e. participants are selected to reflect the diversity of the population)',
  'Stratified Random Sample',
  'Appointment (e.g. city selects members of a consultative council)',
  'Appointment',
  'Election (e.g. consultative council chosen by election)',
  'Election',
  'Not Applicable',
  'Not Applicable'
);

INSERT INTO targeted_participants_case_value_localized VALUES (
  'en',
  'Appointed Public Servants (e.g. bureaucrats)',
  'Appointed Public Servants',
  'Gay/Lesbian/Bisexual/Transgender (i.e. LGBT)',
  'Gay/Lesbian/Bisexual/Transgender',
  'Elderly',
  'Elderly',
  'Elected Public Officials',
  'Elected Public Officials',
  'Experts (e.g. scientists)',
  'Experts',
  'Indigenous People',
  'Indigenous People',
  'Immigrants',
  'Immigrants',
  'Low-Income Earners',
  'Low-Income Earners',
  'Men',
  'Men',
  'People with Disabilities',
  'People with Disabilities',
  'Racial/Ethnic Groups',
  'Racial/Ethnic Groups',
  'Religious Groups',
  'Religious Groups',
  'Stakeholder Organizations (e.g. NGOs, business interests)',
  'Stakeholder Organizations',
  'Students',
  'Students',
  'Women',
  'Women',
  'Youth',
  'Youth'
);

INSERT INTO method_types_case_value_localized VALUES (
  'en',
  'Collaborative approaches (i.e. two or more stakeholders work together to address a common problem)',
  'Collaborative approaches',
  'Community development, organizing, and mobilization (i.e. empowering communities to drive, implement, and effect change)',
  'Community development, organizing, and mobilization',
  'Deliberative and dialogic process (i.e. structured processes that involve deliberation and/or dialogue as a central aspect)',
  'Deliberative and dialogic process',
  'Direct democracy (i.e. formal processes by which citizens exert direct authority over decisions)',
  'Direct democracy',
  'Evaluation, oversight, and social auditing (i.e.monitoring public bodies and services to hold officials and authorities to account)',
  'Evaluation, oversight, and social auditing',
  'Experiential and immersive education (i.e. alternative approaches to teaching and learning)',
  'Experiential and immersive education',
  'Informal conversation spaces (i.e. spaces where deliberation and discussion may take place in an informal or unstructured way)',
  'Informal conversation spaces',
  'Informal participation (i.e. extra-institutional attempts to secure access to resources, rights and political representation without using formal governmental channels)',
  'Informal participation',
  'Internal management or organization (i.e. systems of internal communication, representation, or decision-making)',
  'Internal management or organization',
  'Long-term civic bodies (i.e. sustained efforts to provide the public with opportunities for input and decision-making, typically at the local level)',
  'Long-term civic bodies',
  'Participant-led meetings (i.e. participants shape the agenda and process)',
  'Participant-led meetings',
  'Participatory arts (i.e. processes that engage audiences as participants in the artistic  production or endeavour)',
  'Participatory arts',
  'Planning (i.e. comprehensive approaches to establish goals, policies, and procedures for a social or governmental unit)',
  'Planning',
  'Protest (i.e. direct confrontation with public and/or private institutions)',
  'Protest',
  'Public budgeting (i.e. designed to help decide how public funds should be spent)',
  'Public budgeting',
  'Public meetings (i.e. government-sponsored meetings open to the general public where public officials may also be present)',
  'Public meetings',
  'Research or experimental method (i.e. forms of academic research, or participatory approaches tested as part of a research project)',
  'Research or experimental method'
);

INSERT INTO tool_types_case_value_localized VALUES (
  'en',
  'Manage and/or allocate money or resources (e.g. mobile budgeting applications)',
  'Manage and/or allocate money or resources',
  'Collect, analyze, and/or solicit feedback (e.g. questionnaire; keypad polling)',
  'Collect, analyze, and/or solicit feedback',
  'Facilitate dialogue, discussion, and/or deliberation (e.g. active listening; managing conflict)',
  'Facilitate dialogue, discussion, and/or deliberation',
  'Facilitate decision-making (e.g. ranking; multi-voting)',
  'Facilitate decision-making',
  'Legislation, policy, or frameworks (e.g. arrangements that formally embed public participation)',
  'Legislation, policy, or frameworks',
  'Recruit or select participants (e.g. community outreach; random selection)',
  'Recruit or select participants',
  'Plan, map and/or visualize options and proposals (e.g.GIS mapping)',
  'Plan, map and/or visualize options and proposals',
  'Propose and/or develop policies, ideas, and recommendations (e.g. brainstorming; nominal group technique)',
  'Propose and/or develop policies, ideas, and recommendations',
  'Inform, educate and/or raise awareness (e.g. discussion guide; Q&A with experts)',
  'Inform, educate and/or raise awareness'
);

INSERT INTO legality_case_value_localized VALUES (
  'en',
  'Yes',
  'Yes',
  'No',
  'No',
  'Don’t know',
  'Don’t know'
);

INSERT INTO facilitators_case_value_localized VALUES (
  'en',
  'Yes',
  'Yes',
  'No',
  'No',
  'Not Applicable',
  'Not Applicable'
);

INSERT INTO facilitator_training_case_value_localized VALUES (
  'en',
  'Professional Facilitators',
  'Professional Facilitators',
  'Trained, Nonprofessional Facilitators',
  'Trained, Nonprofessional Facilitators',
  'Untrained, Nonprofessional Facilitators',
  'Untrained, Nonprofessional Facilitators'
);

INSERT INTO facetoface_case_value_localized VALUES (
  'en',
  'Face-to-Face',
  'Face-to-Face',
  'Online',
  'Online',
  'Both',
  'Both'
);

INSERT INTO participants_interaction_case_value_localized VALUES (
  'en',
  'Acting, Drama, or Roleplay',
  'Acting, Drama, or Roleplay',
  'Ask & Answer Questions',
  'Ask & Answer Questions',
  'Discussion, Dialogue, or Deliberation',
  'Discussion, Dialogue, or Deliberation',
  'Express Opinions/Preferences Only',
  'Express Opinions/Preferences Only',
  'Formal Testimony',
  'Formal Testimony',
  'Informal Social Activities',
  'Informal Social Activities',
  'Listen/Watch as Spectator',
  'Listen/Watch as Spectator',
  'Negotiation & Bargaining',
  'Negotiation & Bargaining',
  'Storytelling',
  'Storytelling',
  'Teaching/Instructing',
  'Teaching/Instructing',
  'No Interaction Among Participants',
  'No Interaction Among Participants'
);

INSERT INTO learning_resources_case_value_localized VALUES (
  'en',
  'Expert Presentations',
  'Expert Presentations',
  'Participant Presentations',
  'Participant Presentations',
  'Site Visits',
  'Site Visits',
  'Teach-ins',
  'Teach-ins',
  'Video Presentations (online or in-person)',
  'Video Presentations',
  'Written Briefing Materials (online or as handouts)',
  'Written Briefing Materials',
  'No Information Was Provided to Participants',
  'No Information Was Provided to Participants',
  'Not Relevant to this Type of Initiative',
  'Not Relevant to this Type of Initiative'
);

INSERT INTO decision_methods_case_value_localized VALUES (
  'en',
  'Opinion Survey (i.e. taken before and/or after participants convened)',
  'Opinion Survey',
  'Idea Generation (i.e. potential solutions were generated, but no priorities were decided)',
  'Idea Generation',
  'General Agreement/Consensus (i.e. broad acceptance of decisions; unanimous agreement desired but not necessary)',
  'General Agreement/Consensus',
  'Voting (i.e. any type of formal vote; please provide more detail in next field)',
  'Voting',
  'Not Applicable (e.g. votes are not typically taken at protest demonstrations)',
  'Not Applicable',
  'Don’t Know',
  'Don’t Know'
);

INSERT INTO if_voting_case_value_localized VALUES (
  'en',
  'Preferential Voting (i.e. ranked preferences)',
  'Preferential Voting',
  'Plurality (i.e. highest percentage wins, even if the proposal receives fewer than 50.1% votes)',
  'Plurality',
  'Majoritarian Voting (i.e. 50% +1)',
  'Majoritarian Voting',
  'Super-Majoritarian (i.e. threshold more than 50% +1)',
  'Super-Majoritarian',
  'Unanimous Decision (i.e. full agreement by all participants)',
  'Unanimous Decision',
  'Don’t Know',
  'Don’t Know'
);

INSERT INTO insights_outcomes_case_value_localized VALUES (
  'en',
  'Artistic Expression (e.g. political rap, street theater)',
  'Artistic Expression',
  'Traditional Media (i.e. television, radio, newspapers)',
  'Traditional Media',
  'New Media (e.g. social media, blogging, texting)',
  'New Media',
  'Independent Media (i.e. free of corporate or government influence)',
  'Independent Media',
  'Public Report',
  'Public Report',
  'Minority Report (i.e. a dissenting opinion)',
  'Minority Report',
  'Petitions',
  'Petitions',
  'Protests/Public Demonstrations',
  'Protests/Public Demonstrations',
  'Public Hearings/Meetings',
  'Public Hearings/Meetings',
  'Word of Mouth',
  'Word of Mouth',
  'Not Applicable',
  'Not Applicable'
);

INSERT INTO organizer_type_case_value_localized VALUES (
  'en',
  'Academic Institution',
  'Academic Institution',
  'Activist Network',
  'Activist Network',
  'Community Based Organization',
  'Community Based Organization',
  'Faith-Based Organization',
  'Faith-Based Organization',
  'For-Profit Business',
  'For-Profit Business',
  'Government-Owned Corporation',
  'Government-Owned Corporation',
  'Individual',
  'Individual',
  'International Organization',
  'International Organization',
  'Local Government (e.g. Village, Town, City)',
  'Local Government',
  'National Government',
  'National Government',
  'Non-Governmental Organization (Non-profit)',
  'Non-Governmental Organization',
  'Philanthropic Organization (i.e. dedicated to making monetary grants or gifts)',
  'Philanthropic Organization',
  'Regional Government (e.g. State, Provincial, Territorial)',
  'Regional Government',
  'Social Movement',
  'Social Movement',
  'Labor/Trade Union',
  'Labor/Trade Union',
  'Not Applicable',
  'Not Applicable'
);

INSERT INTO funder_types_case_value_localized VALUES (
  'en',
  'Academic Institution',
  'Academic Institution',
  'Activist Network',
  'Activist Network',
  'Community Based Organization',
  'Community Based Organization',
  'Faith-Based Organization',
  'Faith-Based Organization',
  'For-Profit Business',
  'For-Profit Business',
  'Government-Owned Corporation',
  'Government-Owned Corporation',
  'Individual',
  'Individual',
  'International Organization',
  'International Organization',
  'Local Government (e.g. Village, Town, City)',
  'Local Government',
  'National Government',
  'National Government',
  'Non-Governmental Organization (Non-profit)',
  'Non-Governmental Organization',
  'Philanthropic Organization (i.e. dedicated to making monetary grants or gifts)',
  'Philanthropic Organization',
  'Regional Government (e.g. State, Provincial, Territorial)',
  'Regional Government',
  'Social Movement',
  'Social Movement',
  'Labor/Trade Union',
  'Labor/Trade Union',
  'Not Applicable',
  'Not Applicable'
);

INSERT INTO change_types_case_value_localized VALUES (
  'en',
  'Changes in people’s knowledge, attitudes, and behavior',
  'Changes in people’s knowledge, attitudes, and behavior',
  'Changes in civic capacities (e.g. improved community problem solving)',
  'Changes in civic capacities',
  'Changes in public policy (e.g. new laws or regulations)',
  'Changes in public policy',
  'Changes in how institutions operate (e.g. improved decision making)',
  'Changes in how institutions operate',
  'Conflict transformation',
  'Conflict transformation'
);

INSERT INTO implementers_of_change_case_value_localized VALUES (
  'en',
  'Lay Public (i.e. people with no professional stake in the issues)',
  'Lay Public',
  'Stakeholder Organizations (e.g. community groups, NGOs, business interests)',
  'Stakeholder Organizations',
  'Elected Public Officials',
  'Elected Public Officials',
  'Appointed Public Servants (e.g. bureaucrats)',
  'Appointed Public Servants',
  'Experts (e.g. scientists, engineers, criminologists, doctors, lawyers)',
  'Experts',
  'Corporations',
  'Corporations',
  'Don’t Know',
  'Don’t Know'
);
