-- Get values from the edit localized table, not the view localized table
CREATE OR REPLACE FUNCTION get_case_edit_localized_values(field text, language text) RETURNS localized_value[]
  LANGUAGE sql STABLE
  AS $_$
SELECT array_agg((replace(key, field || '_value_', ''), key, value)::localized_value)
FROM (
  SELECT key, value
  FROM rotate_case_edit_localized(language)
  WHERE key LIKE field || '_value_%'
  ORDER BY key
) as values
;
$_$;


-- update keys to match view data

ALTER TABLE case_edit_localized RENAME COLUMN legality_value_yes TO yes;
ALTER TABLE case_edit_localized DROP COLUMN facilitators_value_yes;
ALTER TABLE case_edit_localized RENAME COLUMN legality_value_no TO no;
ALTER TABLE case_edit_localized DROP COLUMN facilitators_value_no;
ALTER TABLE case_edit_localized ADD COLUMN "false" text DEFAULT 'Localized false';
ALTER TABLE case_edit_localized ADD COLUMN "true" text DEFAULT 'Localized true';
ALTER TABLE case_edit_localized RENAME COLUMN file_upload_label TO files_upload_label ;
ALTER TABLE case_edit_localized RENAME COLUMN file_upload_instructional TO files_upload_instructional ;
ALTER TABLE case_edit_localized RENAME COLUMN file_upload_info TO files_upload_info ;
ALTER TABLE case_edit_localized RENAME COLUMN file_upload_placeholder TO files_upload_placeholder ;
ALTER TABLE case_edit_localized RENAME COLUMN file_link_label TO files_link_label ;
ALTER TABLE case_edit_localized RENAME COLUMN file_link_instructional TO files_link_instructional ;
ALTER TABLE case_edit_localized RENAME COLUMN file_link_info TO files_link_info ;
ALTER TABLE case_edit_localized RENAME COLUMN file_link_placeholder TO files_link_placeholder ;
ALTER TABLE case_edit_localized RENAME COLUMN file_attribution_label TO files_attribution_label ;
ALTER TABLE case_edit_localized RENAME COLUMN file_attribution_instructional TO files_attribution_instructional ;
ALTER TABLE case_edit_localized RENAME COLUMN file_attribution_info TO files_attribution_info ;
ALTER TABLE case_edit_localized RENAME COLUMN file_attribution_placeholder TO files_attribution_placeholder ;
ALTER TABLE case_edit_localized RENAME COLUMN file_title_label TO files_title_label ;
ALTER TABLE case_edit_localized RENAME COLUMN file_title_instructional TO files_title_instructional ;
ALTER TABLE case_edit_localized RENAME COLUMN file_title_info TO files_title_info ;
ALTER TABLE case_edit_localized RENAME COLUMN file_title_placeholder TO files_title_placeholder ;
ALTER TABLE case_edit_localized RENAME COLUMN photo_upload_label TO photos_upload_label ;
ALTER TABLE case_edit_localized RENAME COLUMN photo_upload_instructional TO photos_upload_instructional ;
ALTER TABLE case_edit_localized RENAME COLUMN photo_upload_info TO photos_upload_info ;
ALTER TABLE case_edit_localized RENAME COLUMN photo_upload_placeholder TO photos_upload_placeholder ;
ALTER TABLE case_edit_localized RENAME COLUMN photo_link_label TO photos_link_label ;
ALTER TABLE case_edit_localized RENAME COLUMN photo_link_instructional TO photos_link_instructional ;
ALTER TABLE case_edit_localized RENAME COLUMN photo_link_info TO photos_link_info ;
ALTER TABLE case_edit_localized RENAME COLUMN photo_link_placeholder TO photos_link_placeholder ;
ALTER TABLE case_edit_localized RENAME COLUMN photo_attribution_label TO photos_attribution_label ;
ALTER TABLE case_edit_localized RENAME COLUMN photo_attribution_instructional TO photos_attribution_instructional ;
ALTER TABLE case_edit_localized RENAME COLUMN photo_attribution_info TO photos_attribution_info ;
ALTER TABLE case_edit_localized RENAME COLUMN photo_attribution_placeholder TO photos_attribution_placeholder ;
ALTER TABLE case_edit_localized RENAME COLUMN photo_title_label TO photos_title_label ;
ALTER TABLE case_edit_localized RENAME COLUMN photo_title_instructional TO photos_title_instructional ;
ALTER TABLE case_edit_localized RENAME COLUMN photo_title_info TO photos_title_info ;
ALTER TABLE case_edit_localized RENAME COLUMN photo_title_placeholder TO photos_title_placeholder ;
ALTER TABLE case_edit_localized RENAME COLUMN link_label TO links_label ;
ALTER TABLE case_edit_localized RENAME COLUMN link_instructional TO links_instructional ;
ALTER TABLE case_edit_localized RENAME COLUMN link_info TO links_info ;
ALTER TABLE case_edit_localized RENAME COLUMN link_placeholder TO links_placeholder ;
ALTER TABLE case_edit_localized RENAME COLUMN link_attribution_label TO links_attribution_label ;
ALTER TABLE case_edit_localized RENAME COLUMN link_attribution_instructional TO links_attribution_instructional ;
ALTER TABLE case_edit_localized RENAME COLUMN link_attribution_info TO links_attribution_info ;
ALTER TABLE case_edit_localized RENAME COLUMN link_attribution_placeholder TO links_attribution_placeholder ;
ALTER TABLE case_edit_localized RENAME COLUMN link_title_label TO links_title_label ;
ALTER TABLE case_edit_localized RENAME COLUMN link_title_instructional TO links_title_instructional ;
ALTER TABLE case_edit_localized RENAME COLUMN link_title_info TO links_title_info ;
ALTER TABLE case_edit_localized RENAME COLUMN link_title_placeholder TO links_title_placeholder ;
ALTER TABLE case_edit_localized RENAME COLUMN video_link_label TO videos_link_label ;
ALTER TABLE case_edit_localized RENAME COLUMN video_link_instructional TO videos_link_instructional ;
ALTER TABLE case_edit_localized RENAME COLUMN video_link_info TO videos_link_info ;
ALTER TABLE case_edit_localized RENAME COLUMN video_link_placeholder TO videos_link_placeholder ;
ALTER TABLE case_edit_localized RENAME COLUMN video_attribution_label TO videos_attribution_label ;
ALTER TABLE case_edit_localized RENAME COLUMN video_attribution_instructional TO videos_attribution_instructional ;
ALTER TABLE case_edit_localized RENAME COLUMN video_attribution_info TO videos_attribution_info ;
ALTER TABLE case_edit_localized RENAME COLUMN video_attribution_placeholder TO videos_attribution_placeholder ;
ALTER TABLE case_edit_localized RENAME COLUMN video_title_label TO videos_title_label ;
ALTER TABLE case_edit_localized RENAME COLUMN video_title_instructional TO videos_title_instructional ;
ALTER TABLE case_edit_localized RENAME COLUMN video_title_info TO videos_title_info ;
ALTER TABLE case_edit_localized RENAME COLUMN video_title_placeholder TO videos_title_placeholder ;


-- Sometimes the names in edit table make more sense, but then I have to change all the values too. Ugh.
ALTER TABLE case_edit_localized RENAME COLUMN time_limited_value_single TO time_limited_value_a;
ALTER TABLE case_edit_localized RENAME COLUMN scope_value_city TO "scope_value_city/town";
ALTER TABLE case_edit_localized RENAME COLUMN scope_value_no_limit TO scope_value_no_geo;
ALTER TABLE case_edit_localized RENAME COLUMN purpose_value_public TO purposes_value_make;
ALTER TABLE case_edit_localized RENAME COLUMN purpose_value_private TO purposes_value_make_influence;
ALTER TABLE case_edit_localized RENAME COLUMN purpose_value_goods TO purposes_value_deliver;
ALTER TABLE case_edit_localized RENAME COLUMN purpose_value_civic TO purposes_value_develop;
ALTER TABLE case_edit_localized RENAME COLUMN purpose_value_research TO purposes_value_academic;

-- approaches

ALTER TABLE case_edit_localized RENAME COLUMN approach_value_advocacy TO approaches_value_advocacy;
ALTER TABLE case_edit_localized RENAME COLUMN approach_value_citizenship TO approaches_value_citizenship;
ALTER TABLE case_edit_localized RENAME COLUMN approach_value_civil TO approaches_value_civil;
ALTER TABLE case_edit_localized RENAME COLUMN approach_value_cogovernance TO approaches_value_cogovernance;
ALTER TABLE case_edit_localized RENAME COLUMN approach_value_consultation TO approaches_value_consultation;
ALTER TABLE case_edit_localized RENAME COLUMN approach_value_independent TO approaches_value_independent;
ALTER TABLE case_edit_localized RENAME COLUMN approach_value_leadership TO approaches_value_leadership;
ALTER TABLE case_edit_localized RENAME COLUMN approach_value_protest TO approaches_value_protest;
ALTER TABLE case_edit_localized RENAME COLUMN approach_value_research TO approaches_value_research;
ALTER TABLE case_edit_localized RENAME COLUMN approach_value_public_partner TO approaches_value_coproduction ;
ALTER TABLE case_edit_localized RENAME COLUMN approach_value_private_partner TO approaches_value_coproduction_form ;
ALTER TABLE case_edit_localized RENAME COLUMN approach_value_decision TO approaches_value_direct ;
ALTER TABLE case_edit_localized RENAME COLUMN approach_value_nongovernmental TO approaches_value_informal ;
ALTER TABLE case_edit_localized RENAME COLUMN approach_value_political TO approaches_value_informal_engagement ;
ALTER TABLE case_edit_localized RENAME COLUMN approach_value_auditing TO approaches_value_evaluation ;
ALTER TABLE case_edit_localized RENAME COLUMN approach_value_mobilization TO approaches_value_social ;

-- public spectrum

ALTER TABLE case_edit_localized RENAME COLUMN public_spectrum_value_na TO public_spectrum_value_not;

-- open limited

ALTER TABLE case_edit_localized RENAME COLUMN open_limited_value_all TO open_limited_value_open;
ALTER TABLE case_edit_localized RENAME COLUMN open_limited_value_special TO open_limited_value_open_to;

-- recruitment method

ALTER TABLE case_edit_localized RENAME COLUMN recruitment_method_value_na TO recruitment_method_value_not;
ALTER TABLE case_edit_localized RENAME COLUMN recruitment_method_value_longterm TO recruitment_method_value_civic

-- Targeted participants

ALTER TABLE case_edit_localized RENAME COLUMN targeted_participants_value_disabilities TO targeted_participants_value_people;
ALTER TABLE case_edit_localized RENAME COLUMN targeted_participants_value_ethnic TO targeted_participants_value_racialethnic;
ALTER TABLE case_edit_localized RENAME COLUMN targeted_participants_value_low_income TO targeted_participants_value_lowincome;
ALTER TABLE case_edit_localized RENAME COLUMN targeted_participants_value_stakeholders TO targeted_participants_value_stakeholder;

-- method types

ALTER TABLE case_edit_localized RENAME COLUMN method_types_value_ TO method_types_value_collaborative;
ALTER TABLE case_edit_localized RENAME COLUMN method_types_value_arts TO method_types_value_participatory;
ALTER TABLE case_edit_localized RENAME COLUMN method_types_value_auditing TO method_types_value_evaluation;
ALTER TABLE case_edit_localized RENAME COLUMN method_types_value_budgeting TO method_types_value_public;
ALTER TABLE case_edit_localized RENAME COLUMN method_types_value_community TO method_types_value_longterm;
ALTER TABLE case_edit_localized RENAME COLUMN method_types_value_conversation TO method_types_value_informal;
ALTER TABLE case_edit_localized RENAME COLUMN method_types_value_democracy TO method_types_value_direct;
ALTER TABLE case_edit_localized RENAME COLUMN method_types_value_education TO method_types_value_experiential;
ALTER TABLE case_edit_localized RENAME COLUMN method_types_value_management TO method_types_value_internal;
ALTER TABLE case_edit_localized RENAME COLUMN method_types_value_participant_meetings TO method_types_value_participantled;
ALTER TABLE case_edit_localized RENAME COLUMN method_types_value_participation TO method_types_value_informal_participation;

-- tools, techniques, types

ALTER TABLE case_edit_localized RENAME COLUMN tool_types_value_feedback TO tool_types_collect;
ALTER TABLE case_edit_localized RENAME COLUMN tool_types_value_dialogue TO tool_types_facilitate;
ALTER TABLE case_edit_localized RENAME COLUMN tool_types_value_decisions TO tool_types_facilitate_decisionmaking;
ALTER TABLE case_edit_localized RENAME COLUMN tool_types_value_educate TO tool_types_inform;
ALTER TABLE case_edit_localized RENAME COLUMN tool_types_value_money TO tool_types_manage;
ALTER TABLE case_edit_localized RENAME COLUMN tool_types_value_map TO tool_types_plan;
ALTER TABLE case_edit_localized RENAME COLUMN tool_types_value_policies TO tool_types_propose;

-- legality

ALTER TABLE case_edit_localized RENAME COLUMN legality_value_idk TO legality_value_dont;

-- facetoface or online

ALTER TABLE case_edit_localized RENAME COLUMN facetoface_value_both TO facetoface_online_or_both_value_both;
ALTER TABLE case_edit_localized RENAME COLUMN facetoface_value_facetoface TO facetoface_online_or_both_value_facetoface;
ALTER TABLE case_edit_localized RENAME COLUMN facetoface_value_online TO facetoface_online_or_both_value_online;

-- participants_interactions

ALTER TABLE case_edit_localized RENAME COLUMN participants_interaction_value_bargaining TO participants_interactions_value_negotiation;
ALTER TABLE case_edit_localized RENAME COLUMN participants_interaction_value_dialogue TO participants_interactions_value_discussion;
ALTER TABLE case_edit_localized RENAME COLUMN participants_interaction_value_drama TO participants_interactions_value_acting;
ALTER TABLE case_edit_localized RENAME COLUMN participants_interaction_value_none TO participants_interactions_value_no_interaction;
ALTER TABLE case_edit_localized RENAME COLUMN participants_interaction_value_opinions TO participants_interactions_value_express;
ALTER TABLE case_edit_localized RENAME COLUMN participants_interaction_value_questions TO participants_interactions_value_ask;
ALTER TABLE case_edit_localized RENAME COLUMN participants_interaction_value_social TO participants_interactions_value_informal;
ALTER TABLE case_edit_localized RENAME COLUMN participants_interaction_value_spectator TO participants_interactions_value_listenwatch;
ALTER TABLE case_edit_localized RENAME COLUMN participants_interaction_value_teaching TO participants_interactions_value_teachinginstructing;
ALTER TABLE case_edit_localized RENAME COLUMN participants_interaction_value_testimony TO participants_interactions_value_formal;
ALTER TABLE case_edit_localized RENAME COLUMN participants_interaction_value_storytelling TO participants_interactions_value_storytelling;

-- learning resources

ALTER TABLE case_edit_localized RENAME COLUMN learning_resources_value_na TO learning_resources_value_not;
ALTER TABLE case_edit_localized RENAME COLUMN learning_resources_value_none TO learning_resources_value_no_info;
ALTER TABLE case_edit_localized RENAME COLUMN learning_resources_value_teach TO learning_resources_value_teachins;
ALTER TABLE case_edit_localized RENAME COLUMN learning_resources_value_visits TO learning_resources_value_site;

-- decision methods

ALTER TABLE case_edit_localized RENAME COLUMN decision_methods_value_idk TO decision_methods_value_dont;
ALTER TABLE case_edit_localized RENAME COLUMN decision_methods_value_agreement TO decision_methods_value_general;
ALTER TABLE case_edit_localized RENAME COLUMN decision_methods_value_ideas TO decision_methods_value_idea;

-- if_voting

ALTER TABLE case_edit_localized RENAME COLUMN if_voting_value_super TO if_voting_value_supermajoritarian;
ALTER TABLE case_edit_localized RENAME COLUMN if_voting_value_dk TO if_voting_value_dont;

-- insights_outcomes

ALTER TABLE case_edit_localized RENAME COLUMN insights_outcomes_value_hearings TO insights_outcomes_value_public_hearingsmeetings;
ALTER TABLE case_edit_localized RENAME COLUMN insights_outcomes_value_media TO insights_outcomes_value_traditional;
ALTER TABLE case_edit_localized RENAME COLUMN insights_outcomes_value_protests TO insights_outcomes_value_protestspublic;
ALTER TABLE case_edit_localized RENAME COLUMN insights_outcomes_value_report TO insights_outcomes_value_public;
ALTER TABLE case_edit_localized RENAME COLUMN insights_outcomes_value_social TO insights_outcomes_value_new;
ALTER TABLE case_edit_localized RENAME COLUMN insights_outcomes_value_wordofmouth TO insights_outcomes_value_word;

-- organizer_types

ALTER TABLE case_edit_localized RENAME COLUMN organizer_type_value_academic TO organizer_types_value_academic;
ALTER TABLE case_edit_localized RENAME COLUMN organizer_type_value_activist TO organizer_types_value_activist;
ALTER TABLE case_edit_localized RENAME COLUMN organizer_type_value_business TO organizer_types_value_forprofit;
ALTER TABLE case_edit_localized RENAME COLUMN organizer_type_value_community TO organizer_types_value_community;
ALTER TABLE case_edit_localized RENAME COLUMN organizer_type_value_faith TO organizer_types_value_faithased;
ALTER TABLE case_edit_localized RENAME COLUMN organizer_type_value_government_corp TO organizer_types_value_governmentowned;
ALTER TABLE case_edit_localized RENAME COLUMN organizer_type_value_individual TO organizer_types_value_individual;
ALTER TABLE case_edit_localized RENAME COLUMN organizer_type_value_international TO organizer_types_value_international;
ALTER TABLE case_edit_localized RENAME COLUMN organizer_type_value_labour TO organizer_types_value_labortrade;
ALTER TABLE case_edit_localized RENAME COLUMN organizer_type_value_local_government TO organizer_types_value_local;
ALTER TABLE case_edit_localized RENAME COLUMN organizer_type_value_na TO organizer_types_value_na;
ALTER TABLE case_edit_localized RENAME COLUMN organizer_type_value_national_government TO organizer_types_value_national;
ALTER TABLE case_edit_localized RENAME COLUMN organizer_type_value_ngo TO organizer_types_value_nongovernmental;
ALTER TABLE case_edit_localized RENAME COLUMN organizer_type_value_philanthropic TO organizer_types_value_philanthropic;
ALTER TABLE case_edit_localized RENAME COLUMN organizer_type_value_regional_government TO organizer_types_value_regional;
ALTER TABLE case_edit_localized RENAME COLUMN organizer_type_value_social TO organizer_types_value_social;

-- funder_types

ALTER TABLE case_edit_localized RENAME COLUMN funder_types_value_business TO funder_types_value_forprofit;
ALTER TABLE case_edit_localized RENAME COLUMN funder_types_value_faith TO funder_types_value_faithbased;
ALTER TABLE case_edit_localized RENAME COLUMN funder_types_value_government_corp TO funder_types_value_governmentowned;
ALTER TABLE case_edit_localized RENAME COLUMN funder_types_value_labour TO funder_types_value_labortrade;
ALTER TABLE case_edit_localized RENAME COLUMN funder_types_value_local_government TO funder_types_value_local;
ALTER TABLE case_edit_localized RENAME COLUMN funder_types_value_ngo TO funder_types_value_nongovernmental;
ALTER TABLE case_edit_localized RENAME COLUMN funder_types_value_national_government TO funder_types_value_national;
ALTER TABLE case_edit_localized RENAME COLUMN funder_types_value_regional_government TO funder_types_value_regional;

-- change_types

ALTER TABLE case_edit_localized RENAME COLUMN change_types_value_behaviour TO change_types_value_changes;
ALTER TABLE case_edit_localized RENAME COLUMN change_types_value_capacities TO change_types_value_changes_civic;
ALTER TABLE case_edit_localized RENAME COLUMN change_types_value_operations TO change_types_value_changes_how;
ALTER TABLE case_edit_localized RENAME COLUMN change_types_value_policy TO change_types_value_changes_public;
ALTER TABLE case_edit_localized RENAME COLUMN change_types_value_transformation TO change_types_value_conflict;

-- implementers_of_change

ALTER TABLE case_edit_localized RENAME COLUMN implementers_of_change_value_idk TO implementers_of_change_value_dont;
ALTER TABLE case_edit_localized RENAME COLUMN implementers_of_change_value_public TO implementers_of_change_value_lay;
ALTER TABLE case_edit_localized RENAME COLUMN implementers_of_change_value_stakeholders TO implementers_of_change_value_stakeholder;
