CREATE TABLE case_view_localized (
  language TEXT NOT NULL,
  most_recent_label TEXT DEFAULT 'Localized most_recent_label',
  title_label TEXT DEFAULT 'Localized title_label',
  general_issues_label TEXT DEFAULT 'Localized general_issues_label',
  general_issues_value_agriculture TEXT DEFAULT 'Localized general_issues_value_agriculture',
  general_issues_value_arts TEXT DEFAULT 'Localized general_issues_value_arts',
  general_issues_value_business TEXT DEFAULT 'Localized general_issues_value_business',
  general_issues_value_economics TEXT DEFAULT 'Localized general_issues_value_economics',
  general_issues_value_education TEXT DEFAULT 'Localized general_issues_value_education',
  general_issues_value_energy TEXT DEFAULT 'Localized general_issues_value_energy',
  general_issues_value_environment TEXT DEFAULT 'Localized general_issues_value_environment',
  general_issues_value_governance TEXT DEFAULT 'Localized general_issues_value_governance',
  general_issues_value_health TEXT DEFAULT 'Localized general_issues_value_health',
  general_issues_value_housing TEXT DEFAULT 'Localized general_issues_value_housing',
  general_issues_value_human TEXT DEFAULT 'Localized general_issues_value_human',
  general_issues_value_identity TEXT DEFAULT 'Localized general_issues_value_identity',
  general_issues_value_immigration TEXT DEFAULT 'Localized general_issues_value_immigration',
  general_issues_value_international TEXT DEFAULT 'Localized general_issues_value_international',
  general_issues_value_labor TEXT DEFAULT 'Localized general_issues_value_labor',
  general_issues_value_law TEXT DEFAULT 'Localized general_issues_value_law',
  general_issues_value_media TEXT DEFAULT 'Localized general_issues_value_media',
  general_issues_value_national TEXT DEFAULT 'Localized general_issues_value_national',
  general_issues_value_planning TEXT DEFAULT 'Localized general_issues_value_planning',
  general_issues_value_science TEXT DEFAULT 'Localized general_issues_value_science',
  general_issues_value_social TEXT DEFAULT 'Localized general_issues_value_social',
  general_issues_value_transportation TEXT DEFAULT 'Localized general_issues_value_transportation',
  specific_topics_label TEXT DEFAULT 'Localized specific_topics_label',
  specific_topics_value_abilitydisability TEXT DEFAULT 'Localized specific_topics_value_abilitydisability',
  specific_topics_value_abortion TEXT DEFAULT 'Localized specific_topics_value_abortion',
  specific_topics_value_access TEXT DEFAULT 'Localized specific_topics_value_access',
  specific_topics_value_addiction TEXT DEFAULT 'Localized specific_topics_value_addiction',
  specific_topics_value_administration TEXT DEFAULT 'Localized specific_topics_value_administration',
  specific_topics_value_affordable TEXT DEFAULT 'Localized specific_topics_value_affordable',
  specific_topics_value_age TEXT DEFAULT 'Localized specific_topics_value_age',
  specific_topics_value_aging TEXT DEFAULT 'Localized specific_topics_value_aging',
  specific_topics_value_aging_issues TEXT DEFAULT 'Localized specific_topics_value_aging_issues',
  specific_topics_value_agricultural TEXT DEFAULT 'Localized specific_topics_value_agricultural',
  specific_topics_value_air TEXT DEFAULT 'Localized specific_topics_value_air',
  specific_topics_value_air_travel TEXT DEFAULT 'Localized specific_topics_value_air_travel',
  specific_topics_value_alternative TEXT DEFAULT 'Localized specific_topics_value_alternative',
  specific_topics_value_alternative_education TEXT DEFAULT 'Localized specific_topics_value_alternative_education',
  specific_topics_value_animal TEXT DEFAULT 'Localized specific_topics_value_animal',
  specific_topics_value_arms TEXT DEFAULT 'Localized specific_topics_value_arms',
  specific_topics_value_artificial TEXT DEFAULT 'Localized specific_topics_value_artificial',
  specific_topics_value_bankruptcy TEXT DEFAULT 'Localized specific_topics_value_bankruptcy',
  specific_topics_value_biomedical TEXT DEFAULT 'Localized specific_topics_value_biomedical',
  specific_topics_value_birth TEXT DEFAULT 'Localized specific_topics_value_birth',
  specific_topics_value_budget TEXT DEFAULT 'Localized specific_topics_value_budget',
  specific_topics_value_budget_national TEXT DEFAULT 'Localized specific_topics_value_budget_national',
  specific_topics_value_budget_provincial TEXT DEFAULT 'Localized specific_topics_value_budget_provincial',
  specific_topics_value_bureaucracy TEXT DEFAULT 'Localized specific_topics_value_bureaucracy',
  specific_topics_value_carbon TEXT DEFAULT 'Localized specific_topics_value_carbon',
  specific_topics_value_censorship TEXT DEFAULT 'Localized specific_topics_value_censorship',
  specific_topics_value_child TEXT DEFAULT 'Localized specific_topics_value_child',
  specific_topics_value_citizenship TEXT DEFAULT 'Localized specific_topics_value_citizenship',
  specific_topics_value_civil TEXT DEFAULT 'Localized specific_topics_value_civil',
  specific_topics_value_climate TEXT DEFAULT 'Localized specific_topics_value_climate',
  specific_topics_value_coal TEXT DEFAULT 'Localized specific_topics_value_coal',
  specific_topics_value_cohousing TEXT DEFAULT 'Localized specific_topics_value_cohousing',
  specific_topics_value_community TEXT DEFAULT 'Localized specific_topics_value_community',
  specific_topics_value_community_resettlement TEXT DEFAULT 'Localized specific_topics_value_community_resettlement',
  specific_topics_value_concentration TEXT DEFAULT 'Localized specific_topics_value_concentration',
  specific_topics_value_constitutional TEXT DEFAULT 'Localized specific_topics_value_constitutional',
  specific_topics_value_consumer TEXT DEFAULT 'Localized specific_topics_value_consumer',
  specific_topics_value_copyrights TEXT DEFAULT 'Localized specific_topics_value_copyrights',
  specific_topics_value_corporate TEXT DEFAULT 'Localized specific_topics_value_corporate',
  specific_topics_value_court TEXT DEFAULT 'Localized specific_topics_value_court',
  specific_topics_value_criminal TEXT DEFAULT 'Localized specific_topics_value_criminal',
  specific_topics_value_cultural TEXT DEFAULT 'Localized specific_topics_value_cultural',
  specific_topics_value_curriculum TEXT DEFAULT 'Localized specific_topics_value_curriculum',
  specific_topics_value_cyber TEXT DEFAULT 'Localized specific_topics_value_cyber',
  specific_topics_value_cycling TEXT DEFAULT 'Localized specific_topics_value_cycling',
  specific_topics_value_diplomacy TEXT DEFAULT 'Localized specific_topics_value_diplomacy',
  specific_topics_value_disability TEXT DEFAULT 'Localized specific_topics_value_disability',
  specific_topics_value_disabled TEXT DEFAULT 'Localized specific_topics_value_disabled',
  specific_topics_value_disaster TEXT DEFAULT 'Localized specific_topics_value_disaster',
  specific_topics_value_disease TEXT DEFAULT 'Localized specific_topics_value_disease',
  specific_topics_value_drug TEXT DEFAULT 'Localized specific_topics_value_drug',
  specific_topics_value_drug_testing TEXT DEFAULT 'Localized specific_topics_value_drug_testing',
  specific_topics_value_early TEXT DEFAULT 'Localized specific_topics_value_early',
  specific_topics_value_ecohousing TEXT DEFAULT 'Localized specific_topics_value_ecohousing',
  specific_topics_value_economic TEXT DEFAULT 'Localized specific_topics_value_economic',
  specific_topics_value_economic_inequality TEXT DEFAULT 'Localized specific_topics_value_economic_inequality',
  specific_topics_value_elderly TEXT DEFAULT 'Localized specific_topics_value_elderly',
  specific_topics_value_elderly_housing TEXT DEFAULT 'Localized specific_topics_value_elderly_housing',
  specific_topics_value_electricity TEXT DEFAULT 'Localized specific_topics_value_electricity',
  specific_topics_value_elementary TEXT DEFAULT 'Localized specific_topics_value_elementary',
  specific_topics_value_employee TEXT DEFAULT 'Localized specific_topics_value_employee',
  specific_topics_value_energy TEXT DEFAULT 'Localized specific_topics_value_energy',
  specific_topics_value_energy_efficiency TEXT DEFAULT 'Localized specific_topics_value_energy_efficiency',
  specific_topics_value_energy_siting TEXT DEFAULT 'Localized specific_topics_value_energy_siting',
  specific_topics_value_environmental TEXT DEFAULT 'Localized specific_topics_value_environmental',
  specific_topics_value_ethnicracial TEXT DEFAULT 'Localized specific_topics_value_ethnicracial',
  specific_topics_value_ethnicracial_relations TEXT DEFAULT 'Localized specific_topics_value_ethnicracial_relations',
  specific_topics_value_fair TEXT DEFAULT 'Localized specific_topics_value_fair',
  specific_topics_value_financing TEXT DEFAULT 'Localized specific_topics_value_financing',
  specific_topics_value_fisheries TEXT DEFAULT 'Localized specific_topics_value_fisheries',
  specific_topics_value_food TEXT DEFAULT 'Localized specific_topics_value_food',
  specific_topics_value_food_assistance TEXT DEFAULT 'Localized specific_topics_value_food_assistance',
  specific_topics_value_food_inspection TEXT DEFAULT 'Localized specific_topics_value_food_inspection',
  specific_topics_value_foreign TEXT DEFAULT 'Localized specific_topics_value_foreign',
  specific_topics_value_freedom TEXT DEFAULT 'Localized specific_topics_value_freedom',
  specific_topics_value_freedom_of TEXT DEFAULT 'Localized specific_topics_value_freedom_of',
  specific_topics_value_funding TEXT DEFAULT 'Localized specific_topics_value_funding',
  specific_topics_value_gender TEXT DEFAULT 'Localized specific_topics_value_gender',
  specific_topics_value_gender_identity TEXT DEFAULT 'Localized specific_topics_value_gender_identity',
  specific_topics_value_geopolitics TEXT DEFAULT 'Localized specific_topics_value_geopolitics',
  specific_topics_value_geotechnology TEXT DEFAULT 'Localized specific_topics_value_geotechnology',
  specific_topics_value_government TEXT DEFAULT 'Localized specific_topics_value_government',
  specific_topics_value_government_funding TEXT DEFAULT 'Localized specific_topics_value_government_funding',
  specific_topics_value_government_spending TEXT DEFAULT 'Localized specific_topics_value_government_spending',
  specific_topics_value_government_subsidies TEXT DEFAULT 'Localized specific_topics_value_government_subsidies',
  specific_topics_value_government_transparency TEXT DEFAULT 'Localized specific_topics_value_government_transparency',
  specific_topics_value_hazardous TEXT DEFAULT 'Localized specific_topics_value_hazardous',
  specific_topics_value_health TEXT DEFAULT 'Localized specific_topics_value_health',
  specific_topics_value_health_insurance TEXT DEFAULT 'Localized specific_topics_value_health_insurance',
  specific_topics_value_higher TEXT DEFAULT 'Localized specific_topics_value_higher',
  specific_topics_value_highway TEXT DEFAULT 'Localized specific_topics_value_highway',
  specific_topics_value_homelessness TEXT DEFAULT 'Localized specific_topics_value_homelessness',
  specific_topics_value_housing TEXT DEFAULT 'Localized specific_topics_value_housing',
  specific_topics_value_human TEXT DEFAULT 'Localized specific_topics_value_human',
  specific_topics_value_human_trafficking TEXT DEFAULT 'Localized specific_topics_value_human_trafficking',
  specific_topics_value_identity TEXT DEFAULT 'Localized specific_topics_value_identity',
  specific_topics_value_immigration TEXT DEFAULT 'Localized specific_topics_value_immigration',
  specific_topics_value_indigenous TEXT DEFAULT 'Localized specific_topics_value_indigenous',
  specific_topics_value_indigenous_planning TEXT DEFAULT 'Localized specific_topics_value_indigenous_planning',
  specific_topics_value_industrial TEXT DEFAULT 'Localized specific_topics_value_industrial',
  specific_topics_value_industrial_siting TEXT DEFAULT 'Localized specific_topics_value_industrial_siting',
  specific_topics_value_information TEXT DEFAULT 'Localized specific_topics_value_information',
  specific_topics_value_infrastructure TEXT DEFAULT 'Localized specific_topics_value_infrastructure',
  specific_topics_value_intellectual TEXT DEFAULT 'Localized specific_topics_value_intellectual',
  specific_topics_value_intelligence TEXT DEFAULT 'Localized specific_topics_value_intelligence',
  specific_topics_value_intergovernmental TEXT DEFAULT 'Localized specific_topics_value_intergovernmental',
  specific_topics_value_international TEXT DEFAULT 'Localized specific_topics_value_international',
  specific_topics_value_internet TEXT DEFAULT 'Localized specific_topics_value_internet',
  specific_topics_value_internet_governance TEXT DEFAULT 'Localized specific_topics_value_internet_governance',
  specific_topics_value_jails TEXT DEFAULT 'Localized specific_topics_value_jails',
  specific_topics_value_judicial TEXT DEFAULT 'Localized specific_topics_value_judicial',
  specific_topics_value_labor TEXT DEFAULT 'Localized specific_topics_value_labor',
  specific_topics_value_land TEXT DEFAULT 'Localized specific_topics_value_land',
  specific_topics_value_lgbtq TEXT DEFAULT 'Localized specific_topics_value_lgbtq',
  specific_topics_value_libraries TEXT DEFAULT 'Localized specific_topics_value_libraries',
  specific_topics_value_longterm TEXT DEFAULT 'Localized specific_topics_value_longterm',
  specific_topics_value_lowincome TEXT DEFAULT 'Localized specific_topics_value_lowincome',
  specific_topics_value_maritime TEXT DEFAULT 'Localized specific_topics_value_maritime',
  specific_topics_value_masspublic TEXT DEFAULT 'Localized specific_topics_value_masspublic',
  specific_topics_value_medical TEXT DEFAULT 'Localized specific_topics_value_medical',
  specific_topics_value_mental TEXT DEFAULT 'Localized specific_topics_value_mental',
  specific_topics_value_migrant TEXT DEFAULT 'Localized specific_topics_value_migrant',
  specific_topics_value_military TEXT DEFAULT 'Localized specific_topics_value_military',
  specific_topics_value_monetary TEXT DEFAULT 'Localized specific_topics_value_monetary',
  specific_topics_value_museums TEXT DEFAULT 'Localized specific_topics_value_museums',
  specific_topics_value_nanotechnology TEXT DEFAULT 'Localized specific_topics_value_nanotechnology',
  specific_topics_value_natural TEXT DEFAULT 'Localized specific_topics_value_natural',
  specific_topics_value_natural_resource TEXT DEFAULT 'Localized specific_topics_value_natural_resource',
  specific_topics_value_nuclear TEXT DEFAULT 'Localized specific_topics_value_nuclear',
  specific_topics_value_open TEXT DEFAULT 'Localized specific_topics_value_open',
  specific_topics_value_pensions TEXT DEFAULT 'Localized specific_topics_value_pensions',
  specific_topics_value_police TEXT DEFAULT 'Localized specific_topics_value_police',
  specific_topics_value_political TEXT DEFAULT 'Localized specific_topics_value_political',
  specific_topics_value_political_rights TEXT DEFAULT 'Localized specific_topics_value_political_rights',
  specific_topics_value_poverty TEXT DEFAULT 'Localized specific_topics_value_poverty',
  specific_topics_value_public TEXT DEFAULT 'Localized specific_topics_value_public',
  specific_topics_value_public_art TEXT DEFAULT 'Localized specific_topics_value_public_art',
  specific_topics_value_public_participation TEXT DEFAULT 'Localized specific_topics_value_public_participation',
  specific_topics_value_public_safety TEXT DEFAULT 'Localized specific_topics_value_public_safety',
  specific_topics_value_quality TEXT DEFAULT 'Localized specific_topics_value_quality',
  specific_topics_value_railroads TEXT DEFAULT 'Localized specific_topics_value_railroads',
  specific_topics_value_recycling TEXT DEFAULT 'Localized specific_topics_value_recycling',
  specific_topics_value_refugee TEXT DEFAULT 'Localized specific_topics_value_refugee',
  specific_topics_value_refugee_rights TEXT DEFAULT 'Localized specific_topics_value_refugee_rights',
  specific_topics_value_regional TEXT DEFAULT 'Localized specific_topics_value_regional',
  specific_topics_value_regionalism TEXT DEFAULT 'Localized specific_topics_value_regionalism',
  specific_topics_value_regulation TEXT DEFAULT 'Localized specific_topics_value_regulation',
  specific_topics_value_regulatory TEXT DEFAULT 'Localized specific_topics_value_regulatory',
  specific_topics_value_religious TEXT DEFAULT 'Localized specific_topics_value_religious',
  specific_topics_value_research TEXT DEFAULT 'Localized specific_topics_value_research',
  specific_topics_value_resilience TEXT DEFAULT 'Localized specific_topics_value_resilience',
  specific_topics_value_right TEXT DEFAULT 'Localized specific_topics_value_right',
  specific_topics_value_right_to TEXT DEFAULT 'Localized specific_topics_value_right_to',
  specific_topics_value_roads TEXT DEFAULT 'Localized specific_topics_value_roads',
  specific_topics_value_rural TEXT DEFAULT 'Localized specific_topics_value_rural',
  specific_topics_value_school TEXT DEFAULT 'Localized specific_topics_value_school',
  specific_topics_value_selfdriving TEXT DEFAULT 'Localized specific_topics_value_selfdriving',
  specific_topics_value_sentencing TEXT DEFAULT 'Localized specific_topics_value_sentencing',
  specific_topics_value_social TEXT DEFAULT 'Localized specific_topics_value_social',
  specific_topics_value_space TEXT DEFAULT 'Localized specific_topics_value_space',
  specific_topics_value_special TEXT DEFAULT 'Localized specific_topics_value_special',
  specific_topics_value_species TEXT DEFAULT 'Localized specific_topics_value_species',
  specific_topics_value_sports TEXT DEFAULT 'Localized specific_topics_value_sports',
  specific_topics_value_substance TEXT DEFAULT 'Localized specific_topics_value_substance',
  specific_topics_value_sustainable TEXT DEFAULT 'Localized specific_topics_value_sustainable',
  specific_topics_value_taxation TEXT DEFAULT 'Localized specific_topics_value_taxation',
  specific_topics_value_teacher TEXT DEFAULT 'Localized specific_topics_value_teacher',
  specific_topics_value_telephone TEXT DEFAULT 'Localized specific_topics_value_telephone',
  specific_topics_value_terrorism TEXT DEFAULT 'Localized specific_topics_value_terrorism',
  specific_topics_value_torture TEXT DEFAULT 'Localized specific_topics_value_torture',
  specific_topics_value_tourism TEXT DEFAULT 'Localized specific_topics_value_tourism',
  specific_topics_value_trade TEXT DEFAULT 'Localized specific_topics_value_trade',
  specific_topics_value_transparency TEXT DEFAULT 'Localized specific_topics_value_transparency',
  specific_topics_value_transportation TEXT DEFAULT 'Localized specific_topics_value_transportation',
  specific_topics_value_treaties TEXT DEFAULT 'Localized specific_topics_value_treaties',
  specific_topics_value_unemployment TEXT DEFAULT 'Localized specific_topics_value_unemployment',
  specific_topics_value_unofficial TEXT DEFAULT 'Localized specific_topics_value_unofficial',
  specific_topics_value_vocational TEXT DEFAULT 'Localized specific_topics_value_vocational',
  specific_topics_value_wage TEXT DEFAULT 'Localized specific_topics_value_wage',
  specific_topics_value_walkingpedestrian TEXT DEFAULT 'Localized specific_topics_value_walkingpedestrian',
  specific_topics_value_waste TEXT DEFAULT 'Localized specific_topics_value_waste',
  specific_topics_value_water TEXT DEFAULT 'Localized specific_topics_value_water',
  specific_topics_value_weather TEXT DEFAULT 'Localized specific_topics_value_weather',
  specific_topics_value_wilderness TEXT DEFAULT 'Localized specific_topics_value_wilderness',
  specific_topics_value_worker TEXT DEFAULT 'Localized specific_topics_value_worker',
  specific_topics_value_workforce TEXT DEFAULT 'Localized specific_topics_value_workforce',
  specific_topics_value_youth TEXT DEFAULT 'Localized specific_topics_value_youth',
  specific_topics_value_youth_issues TEXT DEFAULT 'Localized specific_topics_value_youth_issues',
  brief_description_label TEXT DEFAULT 'Localized brief_description_label',
  body_label TEXT DEFAULT 'Localized body_label',
  tags_label TEXT DEFAULT 'Localized tags_label',
  tags_value_accessibility TEXT DEFAULT 'Localized tags_value_accessibility',
  tags_value_activism TEXT DEFAULT 'Localized tags_value_activism',
  tags_value_agenda TEXT DEFAULT 'Localized tags_value_agenda',
  tags_value_animal TEXT DEFAULT 'Localized tags_value_animal',
  tags_value_architecture TEXT DEFAULT 'Localized tags_value_architecture',
  tags_value_capacity TEXT DEFAULT 'Localized tags_value_capacity',
  tags_value_civic TEXT DEFAULT 'Localized tags_value_civic',
  tags_value_civic_roles TEXT DEFAULT 'Localized tags_value_civic_roles',
  tags_value_civil TEXT DEFAULT 'Localized tags_value_civil',
  tags_value_conflict TEXT DEFAULT 'Localized tags_value_conflict',
  tags_value_decisionmaking TEXT DEFAULT 'Localized tags_value_decisionmaking',
  tags_value_democratic TEXT DEFAULT 'Localized tags_value_democratic',
  tags_value_dialogue TEXT DEFAULT 'Localized tags_value_dialogue',
  tags_value_digitalnew TEXT DEFAULT 'Localized tags_value_digitalnew',
  tags_value_direct TEXT DEFAULT 'Localized tags_value_direct',
  tags_value_educational TEXT DEFAULT 'Localized tags_value_educational',
  tags_value_empowerment TEXT DEFAULT 'Localized tags_value_empowerment',
  tags_value_environment TEXT DEFAULT 'Localized tags_value_environment',
  tags_value_formalstructured TEXT DEFAULT 'Localized tags_value_formalstructured',
  tags_value_gender TEXT DEFAULT 'Localized tags_value_gender',
  tags_value_global TEXT DEFAULT 'Localized tags_value_global',
  tags_value_human TEXT DEFAULT 'Localized tags_value_human',
  tags_value_inclusiveness TEXT DEFAULT 'Localized tags_value_inclusiveness',
  tags_value_indigenous TEXT DEFAULT 'Localized tags_value_indigenous',
  tags_value_informal TEXT DEFAULT 'Localized tags_value_informal',
  tags_value_internal TEXT DEFAULT 'Localized tags_value_internal',
  tags_value_initiative TEXT DEFAULT 'Localized tags_value_initiative',
  tags_value_mapping TEXT DEFAULT 'Localized tags_value_mapping',
  tags_value_online TEXT DEFAULT 'Localized tags_value_online',
  tags_value_oversight TEXT DEFAULT 'Localized tags_value_oversight',
  tags_value_participatory TEXT DEFAULT 'Localized tags_value_participatory',
  tags_value_planning TEXT DEFAULT 'Localized tags_value_planning',
  tags_value_political TEXT DEFAULT 'Localized tags_value_political',
  tags_value_public TEXT DEFAULT 'Localized tags_value_public',
  tags_value_public_services TEXT DEFAULT 'Localized tags_value_public_services',
  tags_value_race TEXT DEFAULT 'Localized tags_value_race',
  tags_value_researchstudy TEXT DEFAULT 'Localized tags_value_researchstudy',
  tags_value_rural TEXT DEFAULT 'Localized tags_value_rural',
  tags_value_science TEXT DEFAULT 'Localized tags_value_science',
  tags_value_social TEXT DEFAULT 'Localized tags_value_social',
  tags_value_social_welfare TEXT DEFAULT 'Localized tags_value_social_welfare',
  tags_value_stakeholder TEXT DEFAULT 'Localized tags_value_stakeholder',
  tags_value_storytelling TEXT DEFAULT 'Localized tags_value_storytelling',
  tags_value_sustainability TEXT DEFAULT 'Localized tags_value_sustainability',
  tags_value_transparency TEXT DEFAULT 'Localized tags_value_transparency',
  tags_value_urban TEXT DEFAULT 'Localized tags_value_urban',
  tags_value_youth TEXT DEFAULT 'Localized tags_value_youth',
  location_label TEXT DEFAULT 'Localized location_label',
  scope_label TEXT DEFAULT 'Localized scope_label',
  scope_value_organization TEXT DEFAULT 'Localized scope_value_organization',
  scope_value_neighbourhood TEXT DEFAULT 'Localized scope_value_neighbourhood',
  scope_value_citytown TEXT DEFAULT 'Localized scope_value_citytown',
  scope_value_metropolitan TEXT DEFAULT 'Localized scope_value_metropolitan',
  scope_value_regional TEXT DEFAULT 'Localized scope_value_regional',
  scope_value_national TEXT DEFAULT 'Localized scope_value_national',
  scope_value_multinational TEXT DEFAULT 'Localized scope_value_multinational',
  scope_value_no TEXT DEFAULT 'Localized scope_value_no',
  has_components_label TEXT DEFAULT 'Localized has_components_label',
  is_component_of_label TEXT DEFAULT 'Localized is_component_of_label',
  file_uploads_label TEXT DEFAULT 'Localized file_uploads_label',
  file_links_label TEXT DEFAULT 'Localized file_links_label',
  photos_label TEXT DEFAULT 'Localized photos_label',
  photo_link_label TEXT DEFAULT 'Localized photo_link_label',
  photo_attribution_label TEXT DEFAULT 'Localized photo_attribution_label',
  photo_title_label TEXT DEFAULT 'Localized photo_title_label',
  videos_label TEXT DEFAULT 'Localized videos_label',
  video_attribution_label TEXT DEFAULT 'Localized video_attribution_label',
  video_title_label TEXT DEFAULT 'Localized video_title_label',
  audio_label TEXT DEFAULT 'Localized audio_label',
  audio_attribution_label TEXT DEFAULT 'Localized audio_attribution_label',
  audio_title_label TEXT DEFAULT 'Localized audio_title_label',
  start_date_label TEXT DEFAULT 'Localized start_date_label',
  end_date_label TEXT DEFAULT 'Localized end_date_label',
  ongoing_label TEXT DEFAULT 'Localized ongoing_label',
  ongoing_value_ongoing TEXT DEFAULT 'Localized ongoing_value_ongoing',
  ongoing_value_not TEXT DEFAULT 'Localized ongoing_value_not',
  time_limited_label TEXT DEFAULT 'Localized time_limited_label',
  time_limited_value_a TEXT DEFAULT 'Localized time_limited_value_a',
  time_limited_value_repeated TEXT DEFAULT 'Localized time_limited_value_repeated',
  purpose_label TEXT DEFAULT 'Localized purpose_label',
  purpose_value_make TEXT DEFAULT 'Localized purpose_value_make',
  purpose_value_make_influence TEXT DEFAULT 'Localized purpose_value_make_influence',
  purpose_value_deliver TEXT DEFAULT 'Localized purpose_value_deliver',
  purpose_value_develop TEXT DEFAULT 'Localized purpose_value_develop',
  purpose_value_academic TEXT DEFAULT 'Localized purpose_value_academic',
  approach_label TEXT DEFAULT 'Localized approach_label',
  approach_value_advocacy TEXT DEFAULT 'Localized approach_value_advocacy',
  approach_value_citizenship TEXT DEFAULT 'Localized approach_value_citizenship',
  approach_value_civil TEXT DEFAULT 'Localized approach_value_civil',
  approach_value_cogovernance TEXT DEFAULT 'Localized approach_value_cogovernance',
  approach_value_coproduction TEXT DEFAULT 'Localized approach_value_coproduction',
  approach_value_coproduction_form TEXT DEFAULT 'Localized approach_value_coproduction_form',
  approach_value_consultation TEXT DEFAULT 'Localized approach_value_consultation',
  approach_value_direct TEXT DEFAULT 'Localized approach_value_direct',
  approach_value_independent TEXT DEFAULT 'Localized approach_value_independent',
  approach_value_informal TEXT DEFAULT 'Localized approach_value_informal',
  approach_value_informal_engagement TEXT DEFAULT 'Localized approach_value_informal_engagement',
  approach_value_leadership TEXT DEFAULT 'Localized approach_value_leadership',
  approach_value_evaluation TEXT DEFAULT 'Localized approach_value_evaluation',
  approach_value_protest TEXT DEFAULT 'Localized approach_value_protest',
  approach_value_research TEXT DEFAULT 'Localized approach_value_research',
  approach_value_social TEXT DEFAULT 'Localized approach_value_social',
  approach_value_ TEXT DEFAULT 'Localized approach_value_',
  public_spectrum_label TEXT DEFAULT 'Localized public_spectrum_label',
  public_spectrum_value_inform TEXT DEFAULT 'Localized public_spectrum_value_inform',
  public_spectrum_value_consult TEXT DEFAULT 'Localized public_spectrum_value_consult',
  public_spectrum_value_involve TEXT DEFAULT 'Localized public_spectrum_value_involve',
  public_spectrum_value_collaborate TEXT DEFAULT 'Localized public_spectrum_value_collaborate',
  public_spectrum_value_empower TEXT DEFAULT 'Localized public_spectrum_value_empower',
  public_spectrum_value_not TEXT DEFAULT 'Localized public_spectrum_value_not',
  number_of_participants_label TEXT DEFAULT 'Localized number_of_participants_label',
  open_limited_label TEXT DEFAULT 'Localized open_limited_label',
  open_limited_value_open TEXT DEFAULT 'Localized open_limited_value_open',
  open_limited_value_open_to TEXT DEFAULT 'Localized open_limited_value_open_to',
  open_limited_value_limited TEXT DEFAULT 'Localized open_limited_value_limited',
  open_limited_value_both TEXT DEFAULT 'Localized open_limited_value_both',
  recruitment_method_label TEXT DEFAULT 'Localized recruitment_method_label',
  recruitment_method_value_captive TEXT DEFAULT 'Localized recruitment_method_value_captive',
  recruitment_method_value_random TEXT DEFAULT 'Localized recruitment_method_value_random',
  recruitment_method_value_stratified TEXT DEFAULT 'Localized recruitment_method_value_stratified',
  recruitment_method_value_appointment TEXT DEFAULT 'Localized recruitment_method_value_appointment',
  recruitment_method_value_election TEXT DEFAULT 'Localized recruitment_method_value_election',
  recruitment_method_value_not TEXT DEFAULT 'Localized recruitment_method_value_not',
  targeted_participants_label TEXT DEFAULT 'Localized targeted_participants_label',
  targeted_participants_value_appointed TEXT DEFAULT 'Localized targeted_participants_value_appointed',
  targeted_participants_value_gaylesbianbisexualtransgender TEXT DEFAULT 'Localized targeted_participants_value_gaylesbianbisexualtransgender',
  targeted_participants_value_elderly TEXT DEFAULT 'Localized targeted_participants_value_elderly',
  targeted_participants_value_elected TEXT DEFAULT 'Localized targeted_participants_value_elected',
  targeted_participants_value_experts TEXT DEFAULT 'Localized targeted_participants_value_experts',
  targeted_participants_value_indigenous TEXT DEFAULT 'Localized targeted_participants_value_indigenous',
  targeted_participants_value_immigrants TEXT DEFAULT 'Localized targeted_participants_value_immigrants',
  targeted_participants_value_lowincome TEXT DEFAULT 'Localized targeted_participants_value_lowincome',
  targeted_participants_value_men TEXT DEFAULT 'Localized targeted_participants_value_men',
  targeted_participants_value_people TEXT DEFAULT 'Localized targeted_participants_value_people',
  targeted_participants_value_racialethnic TEXT DEFAULT 'Localized targeted_participants_value_racialethnic',
  targeted_participants_value_religious TEXT DEFAULT 'Localized targeted_participants_value_religious',
  targeted_participants_value_stakeholder TEXT DEFAULT 'Localized targeted_participants_value_stakeholder',
  targeted_participants_value_students TEXT DEFAULT 'Localized targeted_participants_value_students',
  targeted_participants_value_women TEXT DEFAULT 'Localized targeted_participants_value_women',
  targeted_participants_value_youth TEXT DEFAULT 'Localized targeted_participants_value_youth',
  method_types_label TEXT DEFAULT 'Localized method_types_label',
  method_types_value_collaborative TEXT DEFAULT 'Localized method_types_value_collaborative',
  method_types_value_community TEXT DEFAULT 'Localized method_types_value_community',
  method_types_value_deliberative TEXT DEFAULT 'Localized method_types_value_deliberative',
  method_types_value_direct TEXT DEFAULT 'Localized method_types_value_direct',
  method_types_value_evaluation TEXT DEFAULT 'Localized method_types_value_evaluation',
  method_types_value_experiential TEXT DEFAULT 'Localized method_types_value_experiential',
  method_types_value_informal TEXT DEFAULT 'Localized method_types_value_informal',
  method_types_value_informal_participation TEXT DEFAULT 'Localized method_types_value_informal_participation',
  method_types_value_internal TEXT DEFAULT 'Localized method_types_value_internal',
  method_types_value_longterm TEXT DEFAULT 'Localized method_types_value_longterm',
  method_types_value_participantled TEXT DEFAULT 'Localized method_types_value_participantled',
  method_types_value_participatory TEXT DEFAULT 'Localized method_types_value_participatory',
  method_types_value_planning TEXT DEFAULT 'Localized method_types_value_planning',
  method_types_value_protest TEXT DEFAULT 'Localized method_types_value_protest',
  method_types_value_public TEXT DEFAULT 'Localized method_types_value_public',
  method_types_value_public_meetings TEXT DEFAULT 'Localized method_types_value_public_meetings',
  method_types_value_research TEXT DEFAULT 'Localized method_types_value_research',
  tool_types_label TEXT DEFAULT 'Localized tool_types_label',
  tool_types_value_manage TEXT DEFAULT 'Localized tool_types_value_manage',
  tool_types_value_collect TEXT DEFAULT 'Localized tool_types_value_collect',
  tool_types_value_facilitate TEXT DEFAULT 'Localized tool_types_value_facilitate',
  tool_types_value_facilitate_decisionmaking TEXT DEFAULT 'Localized tool_types_value_facilitate_decisionmaking',
  tool_types_value_legislation TEXT DEFAULT 'Localized tool_types_value_legislation',
  tool_types_value_recruit TEXT DEFAULT 'Localized tool_types_value_recruit',
  tool_types_value_plan TEXT DEFAULT 'Localized tool_types_value_plan',
  tool_types_value_propose TEXT DEFAULT 'Localized tool_types_value_propose',
  tool_types_value_inform TEXT DEFAULT 'Localized tool_types_value_inform',
  specific_tools_label TEXT DEFAULT 'Localized specific_tools_label',
  legality_label TEXT DEFAULT 'Localized legality_label',
  legality_value_yes TEXT DEFAULT 'Localized legality_value_yes',
  legality_value_no TEXT DEFAULT 'Localized legality_value_no',
  legality_value_dont TEXT DEFAULT 'Localized legality_value_dont',
  facilitators_label TEXT DEFAULT 'Localized facilitators_label',
  facilitators_value_yes TEXT DEFAULT 'Localized facilitators_value_yes',
  facilitators_value_no TEXT DEFAULT 'Localized facilitators_value_no',
  facilitators_value_na TEXT DEFAULT 'Localized facilitators_value_na',
  facilitator_training_label TEXT DEFAULT 'Localized facilitator_training_label',
  facilitator_training_value_professional TEXT DEFAULT 'Localized facilitator_training_value_professional',
  facilitator_training_value_trained TEXT DEFAULT 'Localized facilitator_training_value_trained',
  facilitator_training_value_untrained TEXT DEFAULT 'Localized facilitator_training_value_untrained',
  facetoface_online_or_both_label TEXT DEFAULT 'Localized facetoface_online_or_both_label',
  facetoface_online_or_both_value_facetoface TEXT DEFAULT 'Localized facetoface_online_or_both_value_facetoface',
  facetoface_online_or_both_value_online TEXT DEFAULT 'Localized facetoface_online_or_both_value_online',
  facetoface_online_or_both_value_both TEXT DEFAULT 'Localized facetoface_online_or_both_value_both',
  participants_interaction_label TEXT DEFAULT 'Localized participants_interaction_label',
  participants_interaction_value_acting TEXT DEFAULT 'Localized participants_interaction_value_acting',
  participants_interaction_value_ask TEXT DEFAULT 'Localized participants_interaction_value_ask',
  participants_interaction_value_discussion TEXT DEFAULT 'Localized participants_interaction_value_discussion',
  participants_interaction_value_express TEXT DEFAULT 'Localized participants_interaction_value_express',
  participants_interaction_value_formal TEXT DEFAULT 'Localized participants_interaction_value_formal',
  participants_interaction_value_informal TEXT DEFAULT 'Localized participants_interaction_value_informal',
  participants_interaction_value_listenwatch TEXT DEFAULT 'Localized participants_interaction_value_listenwatch',
  participants_interaction_value_negotiation TEXT DEFAULT 'Localized participants_interaction_value_negotiation',
  participants_interaction_value_storytelling TEXT DEFAULT 'Localized participants_interaction_value_storytelling',
  participants_interaction_value_teachinginstructing TEXT DEFAULT 'Localized participants_interaction_value_teachinginstructing',
  participants_interaction_value_no TEXT DEFAULT 'Localized participants_interaction_value_no',
  learning_resources_label TEXT DEFAULT 'Localized learning_resources_label',
  learning_resources_value_expert TEXT DEFAULT 'Localized learning_resources_value_expert',
  learning_resources_value_participant TEXT DEFAULT 'Localized learning_resources_value_participant',
  learning_resources_value_site TEXT DEFAULT 'Localized learning_resources_value_site',
  learning_resources_value_teachins TEXT DEFAULT 'Localized learning_resources_value_teachins',
  learning_resources_value_video TEXT DEFAULT 'Localized learning_resources_value_video',
  learning_resources_value_written TEXT DEFAULT 'Localized learning_resources_value_written',
  learning_resources_value_no TEXT DEFAULT 'Localized learning_resources_value_no',
  learning_resources_value_not TEXT DEFAULT 'Localized learning_resources_value_not',
  decision_methods_label TEXT DEFAULT 'Localized decision_methods_label',
  decision_methods_value_opinion TEXT DEFAULT 'Localized decision_methods_value_opinion',
  decision_methods_value_idea TEXT DEFAULT 'Localized decision_methods_value_idea',
  decision_methods_value_general TEXT DEFAULT 'Localized decision_methods_value_general',
  decision_methods_value_voting TEXT DEFAULT 'Localized decision_methods_value_voting',
  decision_methods_value_na TEXT DEFAULT 'Localized decision_methods_value_na',
  decision_methods_value_dont TEXT DEFAULT 'Localized decision_methods_value_dont',
  if_voting_label TEXT DEFAULT 'Localized if_voting_label',
  if_voting_value_preferential TEXT DEFAULT 'Localized if_voting_value_preferential',
  if_voting_value_plurality TEXT DEFAULT 'Localized if_voting_value_plurality',
  if_voting_value_majoritarian TEXT DEFAULT 'Localized if_voting_value_majoritarian',
  if_voting_value_supermajoritarian TEXT DEFAULT 'Localized if_voting_value_supermajoritarian',
  if_voting_value_unanimous TEXT DEFAULT 'Localized if_voting_value_unanimous',
  if_voting_value_dont TEXT DEFAULT 'Localized if_voting_value_dont',
  insights_outcomes_label TEXT DEFAULT 'Localized insights_outcomes_label',
  insights_outcomes_value_artistic TEXT DEFAULT 'Localized insights_outcomes_value_artistic',
  insights_outcomes_value_traditional TEXT DEFAULT 'Localized insights_outcomes_value_traditional',
  insights_outcomes_value_new TEXT DEFAULT 'Localized insights_outcomes_value_new',
  insights_outcomes_value_independent TEXT DEFAULT 'Localized insights_outcomes_value_independent',
  insights_outcomes_value_public TEXT DEFAULT 'Localized insights_outcomes_value_public',
  insights_outcomes_value_minority TEXT DEFAULT 'Localized insights_outcomes_value_minority',
  insights_outcomes_value_petitions TEXT DEFAULT 'Localized insights_outcomes_value_petitions',
  insights_outcomes_value_protestspublic TEXT DEFAULT 'Localized insights_outcomes_value_protestspublic',
  insights_outcomes_value_public_hearingsmeetings TEXT DEFAULT 'Localized insights_outcomes_value_public_hearingsmeetings',
  insights_outcomes_value_word TEXT DEFAULT 'Localized insights_outcomes_value_word',
  insights_outcomes_value_na TEXT DEFAULT 'Localized insights_outcomes_value_na',
  primary_organizer_label TEXT DEFAULT 'Localized primary_organizer_label',
  organizer_types_label TEXT DEFAULT 'Localized organizer_types_label',
  organizer_types_value_academic TEXT DEFAULT 'Localized organizer_types_value_academic',
  organizer_types_value_activist TEXT DEFAULT 'Localized organizer_types_value_activist',
  organizer_types_value_community TEXT DEFAULT 'Localized organizer_types_value_community',
  organizer_types_value_faithbased TEXT DEFAULT 'Localized organizer_types_value_faithbased',
  organizer_types_value_forprofit TEXT DEFAULT 'Localized organizer_types_value_forprofit',
  organizer_types_value_governmentowned TEXT DEFAULT 'Localized organizer_types_value_governmentowned',
  organizer_types_value_individual TEXT DEFAULT 'Localized organizer_types_value_individual',
  organizer_types_value_international TEXT DEFAULT 'Localized organizer_types_value_international',
  organizer_types_value_local TEXT DEFAULT 'Localized organizer_types_value_local',
  organizer_types_value_national TEXT DEFAULT 'Localized organizer_types_value_national',
  organizer_types_value_nongovernmental TEXT DEFAULT 'Localized organizer_types_value_nongovernmental',
  organizer_types_value_philanthropic TEXT DEFAULT 'Localized organizer_types_value_philanthropic',
  organizer_types_value_regional TEXT DEFAULT 'Localized organizer_types_value_regional',
  organizer_types_value_social TEXT DEFAULT 'Localized organizer_types_value_social',
  organizer_types_value_labortrade TEXT DEFAULT 'Localized organizer_types_value_labortrade',
  organizer_types_value_na TEXT DEFAULT 'Localized organizer_types_value_na',
  funder_label TEXT DEFAULT 'Localized funder_label',
  funder_types_label TEXT DEFAULT 'Localized funder_types_label',
  funder_types_value_academic TEXT DEFAULT 'Localized funder_types_value_academic',
  funder_types_value_activist TEXT DEFAULT 'Localized funder_types_value_activist',
  funder_types_value_community TEXT DEFAULT 'Localized funder_types_value_community',
  funder_types_value_faithbased TEXT DEFAULT 'Localized funder_types_value_faithbased',
  funder_types_value_forprofit TEXT DEFAULT 'Localized funder_types_value_forprofit',
  funder_types_value_governmentowned TEXT DEFAULT 'Localized funder_types_value_governmentowned',
  funder_types_value_individual TEXT DEFAULT 'Localized funder_types_value_individual',
  funder_types_value_international TEXT DEFAULT 'Localized funder_types_value_international',
  funder_types_value_local TEXT DEFAULT 'Localized funder_types_value_local',
  funder_types_value_national TEXT DEFAULT 'Localized funder_types_value_national',
  funder_types_value_nongovernmental TEXT DEFAULT 'Localized funder_types_value_nongovernmental',
  funder_types_value_philanthropic TEXT DEFAULT 'Localized funder_types_value_philanthropic',
  funder_types_value_regional TEXT DEFAULT 'Localized funder_types_value_regional',
  funder_types_value_social TEXT DEFAULT 'Localized funder_types_value_social',
  funder_types_value_labortrade TEXT DEFAULT 'Localized funder_types_value_labortrade',
  funder_types_value_na TEXT DEFAULT 'Localized funder_types_value_na',
  staff_label TEXT DEFAULT 'Localized staff_label',
  volunteers_label TEXT DEFAULT 'Localized volunteers_label',
  impact_evidence_label TEXT DEFAULT 'Localized impact_evidence_label',
  change_types_label TEXT DEFAULT 'Localized change_types_label',
  change_types_value_changes TEXT DEFAULT 'Localized change_types_value_changes',
  change_types_value_changes_civic TEXT DEFAULT 'Localized change_types_value_changes_civic',
  change_types_value_changes_public TEXT DEFAULT 'Localized change_types_value_changes_public',
  change_types_value_changes_how TEXT DEFAULT 'Localized change_types_value_changes_how',
  change_types_value_conflict TEXT DEFAULT 'Localized change_types_value_conflict',
  implementers_of_change_label TEXT DEFAULT 'Localized implementers_of_change_label',
  implementers_of_change_value_lay TEXT DEFAULT 'Localized implementers_of_change_value_lay',
  implementers_of_change_value_stakeholder TEXT DEFAULT 'Localized implementers_of_change_value_stakeholder',
  implementers_of_change_value_elected TEXT DEFAULT 'Localized implementers_of_change_value_elected',
  implementers_of_change_value_appointed TEXT DEFAULT 'Localized implementers_of_change_value_appointed',
  implementers_of_change_value_experts TEXT DEFAULT 'Localized implementers_of_change_value_experts',
  implementers_of_change_value_corporations TEXT DEFAULT 'Localized implementers_of_change_value_corporations',
  implementers_of_change_value_dont TEXT DEFAULT 'Localized implementers_of_change_value_dont',
  formal_evaluation_label TEXT DEFAULT 'Localized formal_evaluation_label',
  evaluation_reports_label TEXT DEFAULT 'Localized evaluation_reports_label',
  evaluation_links_label TEXT DEFAULT 'Localized evaluation_links_label'
);

INSERT INTO case_view_localized VALUES (
  'en',
  'Most recent changes by',
  '',
  'General Issues',
  'Agriculture, Forestry, Fishing & Mining Industries',
  'Arts, Culture, & Recreation',
  'Business',
  'Economics',
  'Education',
  'Energy',
  'Environment',
  'Governance & Political Institutions',
  'Health',
  'Housing',
  'Human Rights & Civil Rights',
  'Identity & Diversity',
  'Immigration & Migration',
  'International Affairs',
  'Labor & Work',
  'Law Enforcement, Criminal Justice & Corrections',
  'Media, Telecommunications & Information',
  'National Security',
  'Planning & Development',
  'Science & Technology',
  'Social Welfare',
  'Transportation',
  'Specific Topics',
  'Ability/Disability Issues',
  'Abortion',
  'Access to Radio & Television Frequencies',
  'Addiction Treatment & Management',
  'Administration of Campaigns and Elections',
  'Affordable Housing',
  'Age Discrimination',
  'Aging',
  'Aging Issues',
  'Agricultural Biotechnology',
  'Air Quality',
  'Air Travel',
  'Alternative & Renewable Energy',
  'Alternative Education',
  'Animal Welfare',
  'Arms Control',
  'Artificial Intelligence',
  'Bankruptcy',
  'Biomedical Research & Development',
  'Birth Control',
  'Budget - Local',
  'Budget - National',
  'Budget - Provincial, Regional, State',
  'Bureaucracy',
  'Carbon Capture & Sequestration',
  'Censorship',
  'Child Care',
  'Citizenship & Role of Citizens',
  'Civil Law',
  'Climate Change',
  'Coal',
  'Cohousing',
  'Community & Police Relations',
  'Community Resettlement',
  'Concentration of Media Ownership',
  'Constitutional Reform',
  'Consumer Protection',
  'Copyrights & Patents',
  'Corporate Subsidies',
  'Court Systems',
  'Criminal Law',
  'Cultural Assimilation or Integration',
  'Curriculum & Standards',
  'Cyber Security',
  'Cycling',
  'Diplomacy',
  'Disability Rights',
  'Disabled Assistance',
  'Disaster Preparedness',
  'Disease Prevention',
  'Drug Coverage & Cost',
  'Drug Testing & Regulation',
  'Early Childhood Education',
  'Eco-Housing',
  'Economic Development',
  'Economic Inequality',
  'Elderly Assistance',
  'Elderly Housing',
  'Electricity',
  'Elementary & Secondary Education',
  'Employee Benefits',
  'Energy Conservation',
  'Energy Efficiency & Storage',
  'Energy Siting & Transmission',
  'Environmental Conservation',
  'Ethnic/Racial Equality & Equity',
  'Ethnic/Racial Relations',
  'Fair Labor Standards',
  'Financing of Political Campaigns',
  'Fisheries & Fishing',
  'Food & Nutrition',
  'Food Assistance',
  'Food Inspection & Safety',
  'Foreign Aid',
  'Freedom of Information',
  'Freedom of Speech',
  'Funding',
  'Gender Equality & Equity',
  'Gender Identity',
  'Geopolitics',
  'Geotechnology',
  'Government Corruption',
  'Government Funding of Education',
  'Government Spending',
  'Government Subsidies',
  'Government Transparency',
  'Hazardous Waste',
  'Health Care Reform',
  'Health Insurance',
  'Higher Education',
  'Highway Safety',
  'Homelessness',
  'Housing Planning',
  'Human Rights',
  'Human Trafficking',
  'Identity Politics',
  'Immigration',
  'Indigenous Issues',
  'Indigenous Planning',
  'Industrial Policy',
  'Industrial Siting Guidelines',
  'Information & Communications Technology',
  'Infrastructure',
  'Intellectual Property Rights',
  'Intelligence Gathering',
  'Intergovernmental Relations',
  'International Law',
  'Internet Access',
  'Internet Governance',
  'Jails and Prisons',
  'Judicial Reform',
  'Labor Unions',
  'Land Use',
  'LGBTQ Issues',
  'Libraries',
  'Long-Term Care',
  'Low-income Assistance',
  'Maritime',
  'Mass/Public Transport',
  'Medical Liability',
  'Mental Health',
  'Migrant and Seasonal Labor',
  'Military and Defense',
  'Monetary Policy',
  'Museums',
  'Nanotechnology',
  'Natural Gas & Oil',
  'Natural Resource Management',
  'Nuclear Energy',
  'Open Data',
  'Pensions & Retirement',
  'Police',
  'Political Parties',
  'Political Rights',
  'Poverty',
  'Public Amenities',
  'Public Art',
  'Public Participation',
  'Public Safety',
  'Quality of Health Care',
  'Railroads',
  'Recycling',
  'Refugee Resettlement',
  'Refugee Rights',
  'Regional & Global Governance',
  'Regionalism',
  'Regulation',
  'Regulatory Policy',
  'Religious Rights',
  'Research & Development',
  'Resilience Planning & Design',
  'Right to Adequate Housing',
  'Right to Representation',
  'Roads and Highways',
  'Rural Housing',
  'School Governance',
  'Self-Driving Vehicles',
  'Sentencing Guidelines',
  'Social Determinants of Health',
  'Space Exploration',
  'Special Education',
  'Species Protection',
  'Sports',
  'Substance Abuse',
  'Sustainable Development',
  'Taxation',
  'Teacher Training & Accountability',
  'Telephone Access',
  'Terrorism',
  'Torture',
  'Tourism',
  'Trade and Tariffs',
  'Transparency',
  'Transportation Planning',
  'Treaties',
  'Unemployment',
  'Unofficial (Track II) Diplomacy',
  'Vocational Education & Training',
  'Wage Standards',
  'Walking/Pedestrian Mobility',
  'Waste Disposal',
  'Water Quality',
  'Weather Forecasting',
  'Wilderness Protection',
  'Worker Health & Safety',
  'Workforce Education',
  'Youth Employment',
  'Youth Issues',
  '',
  '',
  'Tags',
  'Accessibility',
  'Activism',
  'Agenda Formation',
  'Animal Protection & Welfare',
  'Architecture & Design',
  'Capacity Building',
  'Civic Infrastructure',
  'Civic Roles & Powers',
  'Civil Infrastructure',
  'Conflict Resolution',
  'Decision-Making',
  'Democratic Innovation',
  'Dialogue & Deliberation',
  'Digital/New Technologies',
  'Direct Action',
  'Educational Resources & Opportunities',
  'Empowerment',
  'Environment',
  'Formal/Structured Participation',
  'Gender',
  'Global Affairs',
  'Human Rights',
  'Inclusiveness',
  'Indigenous Issues',
  'Informal Participation',
  'Internal- & Self-Management',
  'Initiative Process',
  'Mapping & Analysis',
  'Online',
  'Oversight & Monitoring',
  'Participatory Budgeting',
  'Planning & Development',
  'Political Institutions',
  'Public Opinion',
  'Public Services',
  'Race',
  'Research/Study',
  'Rural',
  'Science Communication',
  'Social Media',
  'Social Welfare',
  'Stakeholder Engagement',
  'Storytelling',
  'Sustainability & Green Living',
  'Transparency & Accountability',
  'Urban',
  'Youth & Student Engagement',
  'Primary Location',
  'Scope of Influence',
  'Organization',
  'Neighbourhood',
  'City/Town',
  'Metropolitan Area',
  'Regional',
  'National',
  'Multinational',
  'No Geographical Limits',
  'Components of this Case',
  'Parent of this Case',
  'Files',
  'Links',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  'Start Date',
  'End Date',
  '[No Label]',
  'Ongoing',
  'Not Ongoing',
  'Time Limited or Repeated',
  'A single, defined period of time',
  'Repeated over time',
  'Purpose/Goal',
  'Make, influence, or challenge decisions of government and public bodies',
  'Make, influence, or challenge decisions of private organizations',
  'Deliver goods & services',
  'Develop the civic capacities of individuals, communities, and/or civil society organizations',
  'Academic research',
  'Approach',
  'Advocacy',
  'Citizenship building',
  'Civil society building',
  'Co-governance',
  'Co-production in form of partnership and/or contract with government and/or public bodies',
  'Co-production in form of partnership and/or contract with private organisations',
  'Consultation',
  'Direct decision making',
  'Independent action',
  'Informal engagement by intermediaries with nongovernmental authorities',
  'Informal engagement by intermediaries with political authorities',
  'Leadership development',
  'Evaluation, oversight, & social auditing',
  'Protest',
  'Research',
  'Social mobilization',
  '',
  'Spectrum of Public Participation',
  'Inform',
  'Consult',
  'Involve',
  'Collaborate',
  'Empower',
  'Not applicable or not relevant',
  'Total Number of Participants',
  'Open to All of Limited to Some',
  'Open to All',
  'Open to All With Special Effort to Recruit Some Groups',
  'Limited to Only Some Groups or Individuals',
  'Both',
  'Recruitment Method for Limited Subset of Population',
  'Captive Sample',
  'Random Sample',
  'Stratified Random Sample',
  'Appointment',
  'Election',
  'Not Applicables',
  'Targeted Demographics',
  'Appointed Public Servants',
  'Gay/Lesbian/Bisexual/Transgender',
  'Elderly',
  'Elected Public Officials',
  'Experts',
  'Indigenous People',
  'Immigrants',
  'Low-Income Earners',
  'Men',
  'People with Disabilities',
  'Racial/Ethnic Groups',
  'Religious Groups',
  'Stakeholder Organizations',
  'Students',
  'Women',
  'Youth',
  'General Types of Methods',
  'Collaborative approaches',
  'Community development, organizing, and mobilization',
  'Deliberative and dialogic process',
  'Direct democracy',
  'Evaluation, oversight, and social auditing',
  'Experiential and immersive education',
  'Informal conversation spaces',
  'Informal participation',
  'Internal management or organization',
  'Long-term civic bodies',
  'Participant-led meetings',
  'Participatory arts',
  'Planning',
  'Protest',
  'Public budgeting',
  'Public meetings',
  'Research or experimental method',
  'General Types of Tools/Techniques',
  'Manage and/or allocate money or resources',
  'Collect, analyse and/or solicit feedback',
  'Facilitate dialogue, discussion, and/or deliberation',
  'Facilitate decision-making',
  'Legislation, policy, or frameworks',
  'Recruit or select participants',
  'Plan, map and/or visualise options and proposals',
  'Propose and/or develop policies, ideas, and recommendations',
  'Inform, educate and/or raise awareness',
  'Specific Methods, Tools & Techniques',
  'Legality',
  'Yes',
  'No',
  'Don’t Know',
  'Facilitators',
  'Yes',
  'No',
  'Not Applicable',
  'Facilitator Training',
  'Professional Facilitators',
  'Trained, Nonprofessional Facilitators',
  'Untrained, Nonprofessional Facilitators',
  'Face-to-Face, Online, or Both',
  'Face-to-Face',
  'Online',
  'Both',
  'Types of Interaction Among Participants',
  'Acting, Drama, or Roleplay',
  'Ask & Answer Questions',
  'Discussion, Dialogue, or Deliberation',
  'Express Opinions/Preferences Only',
  'Formal Testimony',
  'Informal Social Activities',
  'Listen/Watch as Spectator',
  'Negotiation & Bargaining',
  'Storytelling',
  'Teaching/Instructing',
  'No Interaction Among Participants',
  'Information & Learning Resources',
  'Expert Presentations',
  'Participant Presentations',
  'Site Visits',
  'Teach-ins',
  'Video Presentations',
  'Written Briefing Materials',
  'No Information Was Provided to Participants',
  'Not Relevant to this Type of Initiative',
  'Decision Methods',
  'Opinion Survey',
  'Idea Generation',
  'General Agreement/Consensus',
  'Voting',
  'Not Applicable',
  'Don’t Know',
  'If Voting',
  'Preferential Voting',
  'Plurality',
  'Majoritarian Voting',
  'Super-Majoritarian',
  'Unanimous Decision',
  'Don’t Know',
  'Communication of Insights & Outcomes',
  'Artistic Expression',
  'Traditional Media',
  'New Media',
  'Independent Media',
  'Public Report',
  'Minority Report',
  'Petitions',
  'Protests/Public Demonstrations',
  'Public Hearings/Meetings',
  'Word of Mouth',
  'Not Applicable',
  'Primary Organizer/Manager',
  'Type of Organizer/Manager',
  'Academic Institution',
  'Activist Network',
  'Community Based Organization',
  'Faith-Based Organization',
  'For-Profit Business',
  'Government-Owned Corporation',
  'Individual',
  'International Organization',
  'Local Government',
  'National Government',
  'Non-Governmental Organization',
  'Philanthropic Organization',
  'Regional Government',
  'Social Movement',
  'Labor/Trade Union',
  'Not Applicable',
  'Funder',
  'Type of Funder',
  'Academic Institution',
  'Activist Network',
  'Community Based Organization',
  'Faith-Based Organization',
  'For-Profit Business',
  'Government-Owned Corporation',
  'Individual',
  'International Organization',
  'Local Government',
  'National Government',
  'Non-Governmental Organization',
  'Philanthropic Organization',
  'Regional Government',
  'Social Movement',
  'Labor/Trade Union',
  'Not Applicable',
  'Staff',
  'Volunteers',
  'Evidence of Impact',
  'Types of Change',
  'Changes in people’s knowledge, attitudes, and behavior',
  'Changes in civic capacities',
  'Changes in public policy',
  'Changes in how institutions operate',
  'Conflict transformation',
  'Implementers of Change',
  'Lay Public',
  'Stakeholder Organizations',
  'Elected Public Officials',
  'Appointed Public Servants',
  'Experts',
  'Corporations',
  'Don’t Know',
  'Formal Evaluation',
  'Evaluation Report Document',
  'Evaluation Report Link'
);
