module.exports = {
  files_label: "Files",
  links_label: "Links",
  videos_label: "Videos",
  audio_label: "Audio",
  ongoing_label: "Ongoing",
  purposes_label: "Purpose/Goal",
  approaches_label: "Approach",
  open_limited_label: "Open to All or Limited to Some?",
  participants_interactions_label: "Types of Interaction Among Participants",
  evaluation_reports_label: "Evaluation Report Documents",
  links_link_label: "Links",
  links_link_instructional: "If there is a main website for this case, enter it here. Add links to additional sources so that readers and editors can find more information about this case online. ",
  links_url_placeholder: "Add link",
  files_instructional: "Upload relevant documents here. Supported file types include: rtf, txt, doc, docx, xls, xlsx, pdf, ppt, pptx, pps, ppsx, odt, ods and odp. Max file size is 5MB.",
  photos_label: "Photos",
  photos_instructional: "Upload images here. Supported file types include: jpg, png, gif and tiff. Max file size is 5MB.",
  open_or_limited_label: "Open to All or Limited to Some?",
  open_or_limited_instructional: "Was this open to all or limited to a subset of the population?",
  open_or_limited_placeholder: "Was this open to all or limited to some?",
  specific_methods_tools_techniques_label: "Specific Methods, Tools & Techniques",
  specific_methods_tools_techniques_instructional: "What specific methods, tools and techniques were used in this case? Type to select from entries already in the Participedia database.",
  specific_methods_tools_techniques_placeholder: "Type to search & generate possible database matches",
  funder_types_placeholder: "Select & rank up to 3 types",
  evaluation_reports_instructional: "Upload relevant documents here. Supported file types include: rtf, txt, doc, docx, xls, xlsx, pdf, ppt, pptx, pps, ppsx, odt, ods and odp. Max file size is 5MB.",
  evaluation_links_link_label: "Evaluation Report Links",
  evaluation_links_link_instructional: "If there is a main website for this case, enter it here. Add links to additional sources so that readers and editors can find more information about this case online. ",
  evaluation_links_url_placeholder: "Add link",
  evaluation_links_attribution_instructional: "Who is the original owner or creator of this linked content?",
  evaluation_links_attribution_placeholder: "Owner or creator",
  evaluation_links_title_instructional: "Provide a title or description of this linked content in 10 words or less.",
  evaluation_links_title_placeholder: "Title or description",
  add_another_link: "Add Another Link",
  audio_link_instructional: "Add links to audio, such as podcasts.",
  audio_url_placeholder: "Add link to audio",
  videos_url_placeholder: "Add link to video",
  audio_attribution_instructional: "Who is the original owner or creator of this audio?",
  audio_attribution_placeholder: "Owner or creator",
  audio_title_instructional: "Provide a title or description of this audio in 10 words or less.",
  audio_title_placeholder: "Title or description",
  scope_of_influence_label: "Scope of Influence",
  scope_of_influence_instructional: "What is the geographical or jurisdictional scope of this case?",
  scope_of_influence_placeholder: "Select geographical or jurisdictional scope",
  body_placeholder: "<h3>Problems and Purpose</h3> <h3>Background</h3> <h3>History and Context</h3> <h3>Organizing, Supporting, and Funding Entities</h3> <h3>Participant Recruitment and Selection</h3> <h3>Methods and Tools Used</h3> <h3>Deliberation, Decisions, and Public Interaction</h3> <h3>Influence, Outcomes, and Effects</h3> <h3>Analysis and Lessons Learned</h3><h3>See Also</h3> <h3>References</h3> <h3>External Links</h3> <h3>Notes</h3>",
  description_label: "Brief Description",
  description_instructional: "Enter tweet-length (280 characters or less) description of this case.",
  facilitators_placeholder: "Did facilitators help guide participants?"
};
